apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:cdRS1TKmVnQ+rfb8PEstkru4mWpx5sATYlsN0WzmWYrlr7jytZo+8g==,iv:6bQQA46TgjE3HhuMCvdDIl4eGtBY3CvemmbdAgxey1c=,tag:8p2yluwKdkBopkzN2k08tQ==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUk5Hb0k3dGw3azYyb1NJ
        SmlROWo4cExTa1hMaHFhaEZORXdpZE5qdEUwCmVCVHJqYUQ1ZHlDOS9DTS9qbDJZ
        K2R1ekNmRDc4aFBXbFN2Z0dSTnlpb1kKLS0tIDJHeWxIdUFrZEFuZCtPbTB3S3hV
        WjFBNk41RWpmWDBzblI3cnc3ZEZuRHMK6qjsnR9wPWN7qwZscdX8hnb7PkcUmJ8t
        mY4pcBjKXpnOCzm9Z/ic4bktBsd/KL5Ak/W2sN/souFKIWErOk9JRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T06:30:03Z"
  mac: ENC[AES256_GCM,data:lZWOnv4qaZ56ManXVGuJu+ywfL2Gnh0tuCKy4jRaCD3f+1GEEeaIRu/tyaM+bpbYbxx0rQi9zoE/BfdyvFsYyA25Ky9zn0DURn1xzv2SM/o9VvBF20Be9yKSd34kHhheAnLE/BBFsS0aThHcWw57iPgnZ19D/JiDK7qycU4SKGM=,iv:AHgKKqIgfuP399E/qQ1zos5Dwzu2pHq7AHyEmyf0IJk=,tag:TrJ2d0+gDf1q3NDm75uIzg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
