apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+VsgmjnrqdxS5g==,iv:E+Hbu9hlqvw5wZkFZvOVqCr6It56bJa8ghNvBci4LfM=,tag:U1CH1D9bShG2NLt6SCyETg==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTCthSmtoVFFSNnliM1pR
        UFFPTi91bjV3M0xnRkhGNEphVzI4MU16Q3dvCnpqUGV3cWNFZGYxYkJnZnZmT04y
        d3EvTW92WGczWEtCRGtWS3V5WjgrQ2sKLS0tIG1ZRDAyV2RvRitXdVE3eWtCTS92
        RDZ3c2U5T1F2YkNucEM2RE5OTml1V1UKU1ZVy7YqVr/F33yio0uHvzNEezvG31Ta
        IAt83foqd9ZJUWr52NaFpOfml37ub/ARf61QIvif7fOHGJOvCcVa4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T06:30:03Z"
  mac: ENC[AES256_GCM,data:kQ1/85kuH5tzfnRMAyaz6mskYgXKUAV2JwmpizwIcLLC6pmLofZtFlYloqQ4IQd2tbIGgdiADa9pgKyYEAEw1DHUKJhy8LArrL4k9Kj1dJA66tvEW6fF3rpI1KFPkuLq6Ype7jeqPjHatEzMcIAA5vyprN/dRtu4Pa37MmyxDyA=,iv:9IIwB9D7ldDPlvaHv528YhFlYcy1wXRsyy0HlQMArfA=,tag:Jf4boa3oS70htDKHvweb9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
