apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:LoRa6xw560rpwaG0/Ep549xLK7hdzMK3QJELdgfDvl4=,iv:TdzYcy0xuwahSjvTyPFzv2NsDG+sBVtZcjRe7vHTkQw=,tag:8VC9LWuSmJaZq2hggutNTQ==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbGgzQmhGN0t4c2dPVHI5
        SVdxU2JoWXBTbUxTSlFzVzEwV3U0UzBqNUMwCmxDWmdmMzhVZ3hSYXR3WTlmd3dl
        VlJoTEJZZWx0VVhlVXFISjl4VEJyOGMKLS0tIHRZREV4Z2xRY2o4N0lrVlEreFAw
        WnVxTFA1azUwbkRDaGNIMExCaXpnb3cKFP918a/T8xEvIlZhfF4+qzBoLrK1wlpW
        D3tczOtVrwf1oPY2v9GiuUpjNzzrzBcbkjgkrTuw7c/6NiGH5ETo9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T06:30:03Z"
  mac: ENC[AES256_GCM,data:FSpm+rZYedzOkYugpdPaUg4FElclvBvxDLsQoheZgrISgTUbmwh9ZeCDnP4nFjbt2ghl5hQgVfPE5DnL7Fvjb7z0+cuaZ4NfWdy7TEPbqQrMHne2/xqOIcPHQ0ZzAR6GJ+JWe0GIoj9fmgGjGy37zY3wSiNqMgTPDEpbAES354s=,iv:OKafyAC/fK8oaVZdtnPGiyklnKeuy62WaSRWM7XfUDM=,tag:kdaGVsIwxRAEcBoyrIigog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
