apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:GCw7ddhlCDWGn5CIZ8s7BNiTjVaf2R7PHJ4q5Fevl9GRSLyrSL/KG/Xa1uPtg5o5KBHb/4kG9JfX9p4hne2VPPOwiJHbA/iCTOt+gQo9xYF8ibuSgRGg7GdKwGKKyFdWcB1xrg2Y8BOGC/VTcpc755qzaNfM+dNK7des4fosxCfF8hZbbP9UPO6gvYjAkgW90NAeMOfxD8NfU7HCWIjIAVCrKrdqQ5ccGAGwtpP1iIu7vJp3,iv:MNp3VCp5nP01HpnNzy4Ns8cbPFoW5ynvXgTPtZ5rPU8=,tag:jD+ncyFMYb6GVX+t4smsZQ==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBob3RtZ09yYVlKTGNLZEcy
        UHJHNitKQkRzOWp5ZGdIWCtxdGdFUGtIbm5zCk5TWWxNT3pGOVVVMXZjb0oxVWx3
        VnY5aGx4ejJmNGpLZ01PbWZ2dTlremcKLS0tIHFkcHdCL0R3ZTNnT3dhZW11TkZF
        MlZBSy9tR1Zoc0lPTEYzQTRhV044ZEUK0ivyg3a/lLIi3J61urpfBqHEhoQE/T77
        sU4ny829XMwBDsO4YByrsqT9R3k4+HY9hzVXJtkhuyyogn/NqvU47A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T06:30:03Z"
  mac: ENC[AES256_GCM,data:EXTFYwS8VtbJ6SZjCkNkPtJ+TeJPMrZKFPUyDV4TNV+f53+JHVx2K462gv5SsCoYDr2CHxqnMYU15RKTwtY7rMz/3H1fqECyW69Kaw/umAITITrg3tAs/b6+EtXIgi/hbeiU52ziZRrImn/yPudCIN6JL/jW4VUK7BMvWMjOGSc=,iv:yNf7PmSDyvuEjZ6HGZ/86BDLuFMI0F4v943v5J8eUlY=,tag:WOawyfVmhfXL0T+jUPmkXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
