apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: headlamp
  namespace: observability
spec:
  endpoints:
    - dnsName: headlamp.${SECRET_DOMAIN}
      recordType: CNAME
      targets:
        - oauth.${SECRET_DOMAIN}
