# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headlamp
  namespace: observability
  annotations:
    external-dns.alpha.kubernetes.io/target: oauth.${SECRET_DOMAIN}
spec:
  hostnames: ["headlamp.${SECRET_DOMAIN}"]
  parentRefs:
    - name: envoy-oauth
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: headlamp
          namespace: observability
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
