apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:vAxlXrHdPXqHNujMj6XIlF0g3KPPW0MV/u6w2jk46+2wckfs9vPbZg==,iv:cRksf8Hz3qhKeIfW+bA4POTE8Xon39o/GqM8NzuIDgY=,tag:XqSFFiaT/LRGWcMC5GtGEw==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSR29qemFIL01Od1NlT2Ns
        VCtpM2Foemdxa2dKc0ZpeXBRTVRmWlpIL0JJClcxYnVNZElWTU1NOENtcG9reHky
        NVFlQ2IxVDlHdzdIUTRYMmtiNW8xUUUKLS0tICtFZ0VGc3A1a2xzbW02WXBIMjN1
        aCtEQjdGMHFTNXZpeGcyNFRLdmhhcDAKUy/dqhHMjpvYyBULQNS/pTQte9aa1bM/
        KZCCcnTggjwrcJIvaNuyNcCMq8OT1k2e1PZjHVBfVZgHEl2HsKAqDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T06:30:03Z"
  mac: ENC[AES256_GCM,data:elpMRpgwIyB+CGgITGqsMYqSlH7sh1SYi+aKychAHvHhtAJPxXc3FXuNqkYmHpBTd+fRmWeiPB2o0maCRtXFm5aHrudK6HUJTIgTBlrYBiAdWKxgIcIn/FTlQFMWLu6side4nYyOx+hOcEGRtR6MLSrX1mLHFDcdCG3nGdr6Jbw=,iv:OcxiGDAh7c3ALROyvc1+jmTebT0jXMyjduc/8XsyTKg=,tag:cx8DLX8K6m9ZPtgDxWzj2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
