apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./certificate.yaml
  - ./envoy.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./podmonitor.yaml
  - ./oauth-client-secret.sops.yaml
  - ./oauth-policy.sops.yaml
  - ./oauth-policy-internal.sops.yaml
