apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-internal-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:QFjeAhX/C9WpRoMJ0Gh2agqcl9QiQTK9WA==,iv:Msr7OasAZz8UJXhmulImSB9gIQeVRoj9uCbVMt+TaiM=,tag:eO9uGCryy+naiII271IJXA==,type:str]
      kind: ENC[AES256_GCM,data:Azhuyv+SSw==,iv:nhOdbcf4xrXBMKVonuqFpfIDcDjzRgDKuy5NLUS1MkQ=,tag:ss16YBblsW1nksr0UqyAnQ==,type:str]
      name: ENC[AES256_GCM,data:ye0Gtaj1BKI1c5sREintgJ4g2A0=,iv:+TaqmLiFAuRIuRugAEpi6HnoR+YYrFY8Jy55fbjolwI=,tag:vFyGpdjET8Je+ACsHAm7bg==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:kVKPUrQuuDiyHkZomGwxhh6IZ1QQSikV3xRR,iv:E93f+lB5eQrw4op8WYlNv7MSRpthV6jiTLYCei9ULgA=,tag:gJVq3Y9Vp6EAIhjfivn5Ow==,type:str]
    clientID: ENC[AES256_GCM,data:ueQUhFihX0VZC5BDZd8VHLyg8wUNpsp3m0q1tnXbSDrBnw0ZVlmq1BGKJQJWr7Vx9Fk7gzZ1o6GMGueY/OEEvHbTT6PE73h4,iv:JhZZazOjjvd1cDHm+2ZttObsiDkjOTP+1EzqzSAhf64=,tag:LPft20eVw9TW6n1MsCXdSA==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:Yc09vtsvSR9nT5tmEjhzTi7MBGxQoZj+734=,iv:6vcI61UevKZlUifneIp3F8qF+pWdTA1UHT5GnYp9tXc=,tag:6GcZQfLBNHNw8JyI/g+Csg==,type:str]
      namespace: ENC[AES256_GCM,data:sWXBqHe37A==,iv:/Q8m5n7v4EeYax4vZJIRtSt1V4ReY8DGFtmbVw9he/c=,tag:lvaqmxFs/exQHlszrS4EnQ==,type:str]
    redirectURL: ENC[AES256_GCM,data:3NU9hj8kaTuqxswZwtR9evbl510GYa57EBeMoi0sQbJYhkx9t73cMN6UnU5h3mHYX7mkE0RJBA==,iv:18bVIYKEjtlkWoT7xcW2YaXIUx7UZB+/j1M2uXKWVys=,tag:b5+ZPOHOw4I46kNHVVYI3w==,type:str]
    logoutPath: ENC[AES256_GCM,data:3EKGk2NJRA==,iv:o42bX7qRp5BR3zJeRmKOuZoagsocBMf8LKk7FQMdFT0=,tag:mRtQHXgIAlvo4Gp1qpbwxw==,type:str]
    cookieDomain: ENC[AES256_GCM,data:B4M4LBOmnuu/JgnorrJROA==,iv:l7Pi7UAEhKGxWmuQn6WHABOWdJLL9UO5Pi3prdU91x0=,tag:FQHX61Nw6gDatwS15HL00g==,type:str]
  jwt:
    providers:
      - name: ENC[AES256_GCM,data:Nph9SXL0,iv:QDw6nCIJ6E3dD6/p/nAAM5DCCzM6xGzwCpzHPTv7o6o=,tag:DrOEN2dsgllK4+iCFg5pmQ==,type:str]
        issuer: ENC[AES256_GCM,data:EYwUfse9ZAsETulO8jvme26I9DAQJOd3rc9m,iv:XcQHtHzrqC6PCS4RSg8CYja42EK+mHQc/Ko4RYyytJE=,tag:SikFhVaFlYaqtCcbPM9KQQ==,type:str]
        remoteJWKS:
          uri: ENC[AES256_GCM,data:d0KcYbhQfXne0f6Hfy81gbCzf2qWKP7Ud71AKNP8iTNPHHTzGg08ukd5,iv:LmBjNYbmJ9TJ1cDH9VWqT+QDCEooz57j3juIITyaTYo=,tag:H6v7Lv0O145o6ZxETZoVkA==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:HJwn3w==,iv:+4i77SqC2cKoluTWA4aBcGvCRyKtCY68k/vGzlnjhlY=,tag:t77Nx/ay4lpzdBeb95JI2Q==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:cIRcQNsUQGOvre2y0k60,iv:4P1bU2S/VkADa6QBW4QFYCqquywg6aqSvyNODyCvHo0=,tag:4/fTgoRCWSqkYzxbI4wIgg==,type:str]
        action: ENC[AES256_GCM,data:TdQwBfU=,iv:YxY/o5qIDwBefeY/PESLBoKqaZN5HD8zvecK35lh/i4=,tag:or1es94gEM2gXdmEFWKO4w==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:NvqCqQBK,iv:M4r8l3IJ4LhcoWbR7ElYO327oFNOOeqIpxmUd5wuKv8=,tag:XJT2VVXCyxXZJ8KhtZLqhQ==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:cmLO7jo=,iv:lpcX0P3io2MAGtbXSMnE/PNOnE2cuMkC68SFqYWD7fY=,tag:AT+uI+FYf8WP/SyLi5AoAg==,type:str]
                values:
                  - ENC[AES256_GCM,data:nY49CIT2Qkpkqr/wO2td0A==,iv:KdNdPjHWrUU+6dr8ZcJQNvipvJ9kK95jnAnPwrPfozU=,tag:rnCicEqJ7OrMd71VpbDvOg==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SzNJSlJJT2lOdW1ML3J5
        N3VrRmowL1F6TEJEN0poT1RtUmFTVDJJalNNClFrb3hBQ3M4T3hYMUF1Q2JVRyt5
        eTdyUXZzZ3pwWG1yTitxRnNnSFdsNDQKLS0tIDkzYVIwQmV6RWlNLzBVQVZwUnZq
        V0VTUzFxQ2hmUzgwZ3o3dlVzckV1ZU0KxWk3cDSjf0FTa44Q/moUbdkcb7w1Q54h
        HaeK4f3cqbPPfv66ZXwu2NjDRvKGre2cqY+WrBUEYVwD4gbhK757dA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T05:52:38Z"
  mac: ENC[AES256_GCM,data:R6uLyj6IyGMXMfiOBzb4SxfOvXXhapO35GXUFEEhj/xs3WYG9PCEhA42JhcBm8daEflEdpkvOtzUw4noSt7fK+HKfAUx4HYMUXKRQoCSbEPocf/6yL02rb8sDeiJsFAkh7uLefzUYuTbA/dEFmvhvgRkQGdAPNSZs38KJMVXIkg=,iv:rh420RmFgsoA/tfKFocTuJ7UZKxOc3zzJ6UBF2jc9kI=,tag:iDTBx+CZMbDzu62YWxAIOA==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
