apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:swE8UBZCofhKHjXg2bmDB0sf8s5LysYcsg==,iv:yzL4SvIZUbHOo106GyVSMsPqR1FCIIIsySJnf7F00Qo=,tag:oXGTqzqWdtgr8CwzEot5tA==,type:str]
      kind: ENC[AES256_GCM,data:YHM65aCuaA==,iv:Le833eqBwsI1gm+FSc4ApFshnYmNzRyH7u9SW9Fh47s=,tag:MOZs6VKLidfE28A8Snf7hQ==,type:str]
      name: ENC[AES256_GCM,data:pOvpQqihLvr/ywI=,iv:fz/4yA5j+Ycat1Qs4yzH4akNQPDuC1pmixueDherIjE=,tag:MEKFNjf0SRasdgh8CM9Odw==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:beVhyNEUkTFx18mBtXHpu1FLYRE+RyItmdVg,iv:QqAJCVeXKp+spfvLQ8FzPZhWb2ydpLPAYof49SIcFvk=,tag:uZ6H2Bu7hef3WGWK8/WoHg==,type:str]
    clientID: ENC[AES256_GCM,data:qIAUWFjeoKkGQrPZXIsN1phlmzdjcqwPhkkzdgNdJZPEuofrvtKnev5Rsw==,iv:GfphZ0JPGDl6mloUthfRtwISG1FhMTniKAZs50mmonQ=,tag:ru6zZ/OXWX95b5kyKuCPCw==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:wjhGTqAmJqvJDk0uD/fTEdkRzLBW3fTwtp8=,iv:4a7HvHd98S35Lmg2O+GIS8fBKOk8KckV47Yo+dJ9U64=,tag:QC3OwfV4Lpy9lbIFhm4E/w==,type:str]
      namespace: ENC[AES256_GCM,data:uxgdFzq/uA==,iv:cl0krHZ9Q6fBSnelJ73U2/Mw08MlWLUoo1ZiDuIe01s=,tag:UfHR267iHqn7j7/t30cV6Q==,type:str]
    redirectURL: ENC[AES256_GCM,data:vEFU3WKNhuyZfVPoO1/cpTxdyl0TxrkxVDBEoDRKEJDVSHOYDrhwYh/jqJbNhA==,iv:doDmxnKRhz5CVfw8TLpIlMsj5OTy3k0qpohM0c5jeeg=,tag:/v9SaBvjstWOMjJYPhjTKQ==,type:str]
    logoutPath: ENC[AES256_GCM,data:Jfwjn8AhFw==,iv:mCL4DOzKZkb05/+1r0YbxtnxsN/BxmjyohNnobEC0sQ=,tag:7gqYjQ1Ul7Y2/p0yxfY00g==,type:str]
    cookieDomain: ENC[AES256_GCM,data:qTnKBAMfPqnX5TROJmATvw==,iv:TiogvVvcCWNNaPVrqeyo12lXKvT9ZymLxy/tL8LcX0g=,tag:o8Pwvf5ucsAk0nv0vS7Epg==,type:str]
  jwt:
    providers:
      - name: ENC[AES256_GCM,data:hbE8inzU,iv:prCMJ9jdxFnY3IdWk5vuy1IK48/eDrf3gi/ki9g21UE=,tag:qrp8U1/B6ldYq+vuvRMZ+Q==,type:str]
        issuer: ENC[AES256_GCM,data:ztRUjDcOosYeKBtMJ/bxcBmQqrk4WC6/qcCS,iv:HXRs/18oeyT6V414WWorfVOo6oAKVOxSEFv3y0OqXdk=,tag:kKbQVV7GafgK9gTdRlxosA==,type:str]
        remoteJWKS:
          uri: ENC[AES256_GCM,data:sr5nBE4UerBIIsR0DZNfMJxeFCOCKPdncnjQwwhC+MwKwKbfxnNNzNHe,iv:Jtt3KB7/47YhvF2VTEa7X+MMQXaOrjWnEnU33QIEOEc=,tag:HSR1/hq6OHS1LVuL5DTMYQ==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:8qNKxw==,iv:3xCUrYMO8Tr2aD+TRLx7G9afM7PqzzWIHYHTma9SJok=,tag:GrukktC8lGHtyMEu1281xg==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:Icit/FXgg6A6ib8gcgsw,iv:7PoUdL1/iwM9htVxYBXFLyAA999Pt896dkhybKe+G0o=,tag:NJyd4m0eheg/K23p0V/UKg==,type:str]
        action: ENC[AES256_GCM,data:/BMTgzY=,iv:d2wmco69WYSld1V+WuwdhYsZ/aHqeZyUxu7Er5H2wi0=,tag:dX/3KUnS0BQQsuDlD9cUDQ==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:1DUjzy97,iv:8qqm8Nh8oOQenDc+RY5u3PECSUlDUIK5qXnTr01cDGY=,tag:ysgcgszE5d3k+W1Kf8EuOQ==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:vPCXXEdfuv9v5bheTfI=,iv:KAQ10S9Fuf+QL//OhXdOXCjCYnyXSQId/YeUO4kVFAY=,tag:0jQO+G7ICTm0INgcIhhNag==,type:str]
                values:
                  - ENC[AES256_GCM,data:Gm8NGg==,iv:FK1BCKF5DoDJXjlVQsBYAgINfiL9KhdxIVcxm2+nfWc=,tag:dCQZITcOwfz6acQ5c4JEvw==,type:str]
              - name: ENC[AES256_GCM,data:z+OPBH8=,iv:sgr0eyf1hMlQQvcylBXq5RoeWRGQAITRht8oFirIV4E=,tag:das878EAgdxDaw6B03wu8A==,type:str]
                values:
                  - ENC[AES256_GCM,data:rQGrZ3yC0B+Kl9YLibs5bjSLZE0raac=,iv:GNHm/ntd38oilSigEXr+18AP5ke3ueCAFCIYs8Hw2VA=,tag:l+huh7AzzhLf8ZQTf2DQ4Q==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVHRPb0MzcldHYmZUdFIz
        ZDVJNlVxbUlqRWxzbEhKNktVRm5yN3VYVnhrClVyL0xUSzVabXRZWllnd0hkQTVh
        K1loREJ2elNwa1hYck03NDRjOXBTamMKLS0tIEhGNVpsaG5vRmFtMGFXbXZHVDVp
        T3R5MFZpQWNMSTMzUTlQRGhKUXc0MWMKin2G+UVSHNnQnZv7j8Nba6O3bKcr7+qd
        Y3tuyEkVATyOgY6cNPdRr8rTbS0NZsHTUFLPbp0ymSy7dOoxr6L0wg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T06:39:55Z"
  mac: ENC[AES256_GCM,data:LbINEU1oqwKgodWMj9O3l6I67Chl2mdRvsjwQWccxyyp2JrfpqSsJZEuH4uU/fm19e5aLAqKcubKDFqOCRlAIi+kX9t9H9raJ9aytc7KghgeK5opTr7rfkLbx8jF89Bq9xBvNqMnOHRITp5MQ+RiGzBIr8UOuahhEVK8Cav19Fs=,iv:CX5ZUJ3Vjj4082HePC/+R16rPLl2woNsjqk+hAA6jO4=,tag:BnGdNKAxkrUyjAYcVDEzUA==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
