apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:Hmymrugrq1YxbEcOGzZp4YFAa0Lk4Yhy5Q==,iv:2eUxCFKdZgH7Q7OjcKUUd7yThgHVoIL32jwcxngqEO0=,tag:jX0gbTuSmK+GkLJz386a2A==,type:str]
      kind: ENC[AES256_GCM,data:ynyLor0wdA==,iv:b9ckjKmXJxL0FNldJhsV/c5I5JA1wRGmmibT1IusGZQ=,tag:mGoU/5xcvfS8QlRI0Y03Sw==,type:str]
      name: ENC[AES256_GCM,data:/nBOO/yGP5ky5LE=,iv:QtGiEpr3dNDqSBRbHeWBBEfajCC/ElU+ULfrRoLktaQ=,tag:9lWS38vAJ8W/nb9CjDdHTA==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:xPA8MZNJBeESN1jItYQDHtMLASoWE0tqJyyC,iv:0ACxzaDsRSQeXFnw9SO4Zs969FUV5uwuZxiaQ4a6H2g=,tag:Hz/1zrZlES4tjibJU9S0yw==,type:str]
      authorizationEndpoint: ENC[AES256_GCM,data:+MY4AO8dUhz1cZ5EsOGDr9hyQ1Mx3GAgrZcefpqT5eYR2AosXZya+05aM/A8aVSZEHVH600iTptyL+SonIB4Avik,iv:YxFNjQzHNUBY3rH2KtGAjGSSkQHuLI1g7kW5Hp+DLmg=,tag:T2Z2uEPHPEoTpuf42v+XCw==,type:str]
    clientID: ENC[AES256_GCM,data:8hOpOUrDl6XsLvMmE7BMp2wRyFFvjIYeYh+QSo5/evuGxE9D841l3tkw7Xe2/4NeicrDXv/3CFaETNUD1ZAih74aIZj6TSQH,iv:kVUAtr5YB/DSoZjewHEDt0BtPd0Y6aKwBbsUl4BX5NU=,tag:kYO/AOVe8BD5Kv0B20rmfg==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:oyPugzCp8U7mDJLcOVOK6m1SEp7XmzxJF+Y=,iv:gmGutZM2JYYfwSzoKLgwtchmRXLx8fflpSX1Nf+MhnQ=,tag:DOAjApmDbzlrmlUu6J8pAg==,type:str]
      namespace: ENC[AES256_GCM,data:Om2B4YNRpw==,iv:LNMJCjQqn+Q3+4oznUi8MARKZqui6zqmPR3WuHEAI3o=,tag:C+i1Px90dIU+9rmRsN93ZQ==,type:str]
    redirectURL: ENC[AES256_GCM,data:aHbURfrSIqThICexaa9MY4TMKTFMAnE7SXNMSPEYMkMtMi+deiTV6dhMKOImDQ==,iv:LD5wHePJw1g9g/rA7kRCKRz8ucUnG7Tkodlrymh+b+U=,tag:ezr31i3qczT7LBap+Q6kCg==,type:str]
    logoutPath: ENC[AES256_GCM,data:wjsVmNJDgA==,iv:kBxtzg1XhC3XGS+pwOUsUmJpdXx2rF5wDJP9SedsuCQ=,tag:gLZ8TgCUv/+MOUFa64PANw==,type:str]
    cookieDomain: ENC[AES256_GCM,data:nIZXFFC6MTPxNJN5U6wrjQ==,iv:SyLyFpCh6i9F300CoWIpym+rF7dDijL1PyPklpjxoD0=,tag:HRkYlJGUJlkzM8O56NFgyw==,type:str]
    cookieNames:
      accessToken: ENC[AES256_GCM,data:QMgXe7iQPCdFJrM=,iv:wOtmxJG9Tma1eWrN2hgtQZDMeX0dpgXcwPfBx/riLD0=,tag:Z68Cj0911toPGaF3TEQ5vQ==,type:str]
      idToken: ENC[AES256_GCM,data:UeSPEPjLmw==,iv:yzhyaAEXGef6+QGSo9X/jE+ixpIuVxuD81bmhKWFP30=,tag:Q8lfOPiHUnExgkdZyNUHcA==,type:str]
    scopes:
      - ENC[AES256_GCM,data:V3qBEJBQ,iv:Hqm/gUv42BSmczPrGOd3EayaFwZICMg3wHJQ3GmQkdY=,tag:OpPMf5sOMkRqCjUylpAUBg==,type:str]
      - ENC[AES256_GCM,data:AoEYM8U=,iv:+D4dq7stU3z0Z/GSmvfbTuBeeH06Stz8ymcrhMEtDHA=,tag:XVIXhZKDSCbV2R3ofmlOaQ==,type:str]
      - ENC[AES256_GCM,data:sPlWdeZSBQ==,iv:9GoMhPsaiGIRboKWtMEYh0yd0CfWG2MddpETW3cMvw4=,tag:zeqLQPidORUiRz6IR0x9fg==,type:str]
  jwt:
    providers:
      - name: ENC[AES256_GCM,data:gWci915x,iv:GcTZ0FD5Fda8lWkvP4i1sCj8c6J1BMzlFXyY0+1Xpqo=,tag:mNrkl16cG3VGo9MniyN+8w==,type:str]
        issuer: ENC[AES256_GCM,data:RpZbhCT4jALwuYU+LPaonYY6DxAfh4tth3F6,iv:dyKiWAYATDYsDd2IOUr2wNpOtVZ2lo+Tucvp27tOXhA=,tag:Qw8ZwKZa6vGz6yDERbbahw==,type:str]
        remoteJWKS:
          uri: ENC[AES256_GCM,data:BP8KFsSiw0rI23c2AGPlkBKBNJ1Bf2JutvFRBT+p9chEQkWPmzmqioCj,iv:Kkfu+Op+NJ2BFPfGdTmrtKqiOVG9nE9j6plZMVUNG4E=,tag:gm/xp+13WMNOYrKt1ul6gQ==,type:str]
        extractFrom:
          cookies:
            - ENC[AES256_GCM,data:3DHUOoq2Mg==,iv:oMcD++NqPdBKp9lQEc/JCK2L+ZhMEuYDxbMV74MIseE=,tag:G6sQ6DafIHhsCclG2HRLfw==,type:str]
          headers:
            - name: ENC[AES256_GCM,data:RzGjxHWG/96YckSiWw==,iv:BNsItd1Vetm6+dzspB8IJf5t7vUOBf0BvirmHG/dRbk=,tag:8HkHAY0ttBgRrdERPTXRXw==,type:str]
              valuePrefix: ENC[AES256_GCM,data:A0CNokUONg==,iv:U5ugcowGclSPFIZV7N9lSH5H3sBHKs1GiaLIdJ9is4A=,tag:0GcOlda4ef9fdQnumRVPAQ==,type:str]
          params:
            - ENC[AES256_GCM,data:JH70ZkpEgm8NdfyP,iv:QYkbsm5TAuxUpPl9j0C5RkUW7+4+DvC4GrQr2peM2FY=,tag:ee+Q552bXX+Q07dMDc4eXA==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:T+KwlA==,iv:pZHlbVjt4PJwsZ+mKU1YEwZkEgwIr4dc3NtdOYcHMHU=,tag:jd4noBTVwRPDUQTgXYDSPA==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:eHt28Yd5mTpkTfeFPVoV,iv:MGYqeEdjj3Fv/4Cj4BSWmNiz0mnj9NiTOPuyCH6NyBU=,tag:awq4jqpMjDxLpcsAn28Rhg==,type:str]
        action: ENC[AES256_GCM,data:7gVwWPE=,iv:in4iQeRFJV8vOPup7rNqwzqFlgCIBg2SlkXdcqhnuxw=,tag:3w/NXf5Skd8rgLdjTlsXsw==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:+qXTyGcU,iv:F+5mqpiIOIKs2al8gjg4ZzO1dHbqnPgm+UQ4iMSoyCo=,tag:269tHkuBzPS+xcQSJn7oFg==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:jUAi2oM=,iv:VZiLOddP5nLHPz1ZjIFhmLc22QNqzjSNgLgh9x7xpLo=,tag:aZT+uOLpO1rTfINBdeCGNA==,type:str]
                values:
                  - ENC[AES256_GCM,data:LOPkKrCOJ98molMsa8i3Vw==,iv:zN4K3Cp83DMdwNSc8mLZwre2MUmMD4kFZuJH6Mn7+Mc=,tag:Yis2coKP17XqN6axC/PaoA==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOE5yYzJ5L2tzN2pqMS9v
        V0tUUEVqeFdERlhiWjNlZ1R4Tktnc2lCSW1RClp5UTZxM2xwU2hYSFlUUHpMMyt6
        UTRwUUZLYWFCTGpLZStrdUU4eEJ0WDgKLS0tIEpmS2xjRW82WHp0UGs3MEI2VEI4
        b3hvT1A1Z25zVk91WHRBeURZT1NiU1kK6HfAclLuYdpePvZkg/hPBYXulZe374kx
        6lPMldewM1qnbzKgl5Nf5NNtBcn5UFAGDdCP/caWKL782SIZm2hw0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T06:07:17Z"
  mac: ENC[AES256_GCM,data:bd+MfC1KWNg4gP0xjdNpOPVoKZ1rsbqNWDzGPjlUERcRHX6hA68dPWsrXNDmCu7zGDkq5a4vthKu6fdcB+JXvoaucjfc8ZP7DBsqLkvwgE3dgmSQsNaYT9tgQH0y4D3/VI32nERy7l82g27YBy9kMnkClxS6iO0YJesX04BdSBY=,iv:8mmVDcn32wj9mm9hX1xU8C0SyoFf1pR8Q4gHqNm/Dqc=,tag:FhlypkgngPu4TCD0vl6c8g==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
