apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:H5pJDOhzJTuoHtMsY/RQTQ69mofwqQyMkg==,iv:JRSmx7ljFhEtETKRR33RBfhDqPYJT5nZsg8qt/YhBaI=,tag:bOTFjIDroRKlpDRJhCNkZw==,type:str]
      kind: ENC[AES256_GCM,data:fjhK9HRGZA==,iv:hzCoIg4W/YuuMiwF102g8Aqb3ags9F6QxmZaSfkDHto=,tag:sXvBMIdHV0O30IXaEGgqLw==,type:str]
      name: ENC[AES256_GCM,data:KIUIl69iLgwOE4A=,iv:Wr9KDWUqOSIEcj2we4HZDYjGOH6bvRhWhSKErjOd6k8=,tag:d2IjjeMiKOqlbz05CgIDqQ==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:OGi6yq6XxsO3kfPb14VPJhFcn6dFOEPT9NK0,iv:0nGHgfNmBKtGN0bkUDqpNDAWxB1Cd51eFUviJ6KS1zo=,tag:ZwO/ATrq1QfRSn272HvVrA==,type:str]
    clientID: ENC[AES256_GCM,data:l4EiBz7IFHF6aF76okVlT1O+bn3QYgnFmnv5B79Py+PuZgDyGGC4zYXDGAnncSB59c8DtTocWJQQ76zTf5z29tFYj8zqyaqo,iv:MeD4JI5Ouhy8IcFlfisLsS0i8ot+NbCSQUaprvS/E80=,tag:3Wmr0no0bUSEMdOsCMninA==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:SOEnp/qoidFj838qFm010p0ptsKqLpBrJHo=,iv:qfPDUykhCg74fb+NOEY97EOb8vC28S+rICojbmXwpwM=,tag:fUU44LMDXnBcNizlBAlevg==,type:str]
      namespace: ENC[AES256_GCM,data:G+k7ytAlOA==,iv:zeb2xwiWv3gKh3yOyc294gm37zcBSZU43PtkOEec81Q=,tag:+3fvLmVh6g1Wia30T2D4uw==,type:str]
    redirectURL: ENC[AES256_GCM,data:cVUeLYmutuuQq9H5ky3pI7N5eeq7xUP8AzgkVmx24VLg1NB6bx0+ewFs4LmJbA==,iv:w2wotdUce363b+xZwOe0zy6A1tr+Bmr4JS1HWMuQh7w=,tag:zXj+ILsYIcwFChMUTR3SEQ==,type:str]
    logoutPath: ENC[AES256_GCM,data:/BnuLUUEwQ==,iv:FtoQqjTrBfByqDms5WfzWMif+g1FYQBTe4XS/sBouUQ=,tag:lKM6mlrx2zOetZBToHsRjg==,type:str]
    cookieDomain: ENC[AES256_GCM,data:Bju+ZyzJ6e4OpkWQ3BVjjQ==,iv:g9kx0gA5jd/m3bParfJzo66fTM/KAErBbWWUh/TJZxU=,tag:D2w9j48PC1/vwEsnWlkn2Q==,type:str]
  jwt:
    providers:
      - name: ENC[AES256_GCM,data:ezqKfotV,iv:pV1o8/0j6z7tBaqUvBBnNY2yGVHQF5e0wrGIG0vmkqU=,tag:BghGSmQBb4+KDU7YWCqlCw==,type:str]
        issuer: ENC[AES256_GCM,data:YC+NWVsmVC8FK8BrwcUnn03odSBRKPrSbdB4,iv:ICXgw52vtnUorANfmc4NPzyKY9bD7WI1sL7QSTqiZ0s=,tag:qX7919scRVROwJuWDBwhvw==,type:str]
        remoteJWKS:
          uri: ENC[AES256_GCM,data:09AeWgsB5P1Y1K1CtaeeS2Yn2qzoVNJlpafNEDMLjc8PnMwzeE0k/GY/,iv:i/aBWOS66O5x1bkq+5sAMtPn50GHTCYQm8hpzd0Vft8=,tag:BEnau9zRlmZnbfh04C+3dQ==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:+h+aNg==,iv:4nT84QoToj/H928n3sstfRzRrsqkVhOjscXSnH4lFNQ=,tag:ZxG+PYKVAXexlNNqqKH8xQ==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:eu+YQ3Z0/XNyVS3pLFlp,iv:bqYBg1Gi1LzAEuZ2azGlvGrIgP3sVzGV+dPB8PQXEd0=,tag:3BwPNKbHuBazKd7H2NgnpA==,type:str]
        action: ENC[AES256_GCM,data:o2Eo8es=,iv:bZBM6LCR7pffAm9dRyGl4+tYXVW5Rr5LAsV9HlhcOEI=,tag:mXmYOEQJ5ks0pp5DjtxuWw==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:S4n6thCS,iv:SkLyGg/4/7X8v4NV6bW6FSgYtdRyYbv25nzR66lNn4o=,tag:udPPiWBOSD+juCjqzYE5VA==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:zCLwayqOSR10FyaD9uc=,iv:wva7yn4U09JDdabDSD3ZQAc0ygY5P38ChymC3ZRxQ/8=,tag:qnjk+A8kGv+4f68sxdIznA==,type:str]
                values:
                  - ENC[AES256_GCM,data:HuwtJw==,iv:KpZOimgfl3Gen19NLBC7/dZnhJMdwR93XVtOsZ+jgPw=,tag:pXW2zmDKYkHLP853dA/YMQ==,type:str]
              - name: ENC[AES256_GCM,data:Se72uYg=,iv:aWFTxlMXhz+acMh9FLsyIMffj0kihFaORVsdzwg8ZkE=,tag:c6Cka2ocHnQgmfrjZgAW9w==,type:str]
                values:
                  - ENC[AES256_GCM,data:JgbI4c7vZbRI1kDjMRY6KQ==,iv:/+00Z+gOJIhSSvE8cHh/9pCEBtsQIAkUk/HRoV7hpBs=,tag:Lc7kg58mhrF7NcERu4bygA==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQTNQaU4wOVNvMEFWRHQ3
        UTYwUFZpSURnb3gzSVV3T0V6a3ZBQ21KN0I0CjBWNWFYV1JhcDVFR1VzTG9HY09o
        RFVHblcrQVhDckhMQk9CWm5qa0F6NzgKLS0tIExTR0xRQW5RU2srNmhBenQ1d0I4
        WWg2L1NnYjY2MCtHR1B4S0lMKzcrNDQK/ngsQntAbtEhetRbTHc9W6KcgmX0+owG
        dPMRE8TgA6SWQk0+vcQuKjWiSsd44ZaZPPWPw8H0tlma3SueKSj3IA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T05:00:50Z"
  mac: ENC[AES256_GCM,data:o8/U06Bx6lOB/VVbw3NXoCAMz03abuHYHkfT0BbnP+sfErNGw/Mykpcy4M50Wtn4ruwvCBYXdO2YZ68IaNWIGh2wqFsdCB6PuB/rjfCrvZfJzvdcxA2lbWygHj3ZzZAy3fmpA4rmzeKAYbykfursMxQEK1V34scDPtuD5E7fdr4=,iv:kJmkD0ExtnECXtXmQ/31MtVb84tCKKbONk/ZmRLT5ho=,tag:BtFw/c0UrIEdHop7KCfHEA==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
