apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-internal-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:f9eqV4LIslgqWw45iJlx3cHGl9lb37t7vw==,iv:yREs7ivmKc+1Di1xejKp7gq+n82VHYp/FQng/TGLOrE=,tag:0Ilyajf/oiOZnE6lSO1EqA==,type:str]
      kind: ENC[AES256_GCM,data:caczMWcgRw==,iv:cKIX080cjHupndMP/sbTwu+mIr6tvF/jLYJLfjBlDBc=,tag:j+DAFzRsOx37ZQv2GQhlZw==,type:str]
      name: ENC[AES256_GCM,data:fme1xJ55ARNQycvQLB0UXTLs42w=,iv:qokGx7Rbeo9fuoIRhUg4HAXGI3EY+GzNDhGyiaRaU80=,tag:xduF2NWVnhZwdC8gz8A9VQ==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:IQAafsjyDZBJud2w9yzVJmXaEqXH8u69MiIM,iv:s3bViI43nlM0KuEtsDs1e5dpzHi0cBdYP/cLi8ogdvU=,tag:qrK496rBOvoG9FR7SJc8GA==,type:str]
    clientID: ENC[AES256_GCM,data:NySj0o5iflYKIgojVEOXh214fN9lC4d+3fcxt4ufa2Ta0TdJeCO6Zd27Zw9CTNVBxZ7xJngZzTrcWLPXbCFvTDy6xu5gAF5h,iv:7HLm1wcgUQlk0xUIqK+0aOQQuB5y4uIn3tYM4YjBU18=,tag:M9nwrJENBCoiqvxxJBkE2Q==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:fs64+cRpkLf3Cheab2/aNhOcWDJi8qd8iXI=,iv:4SNX3mbwjUczKVIqqeRmm7tmCh2T/qN9TzATGs10B0A=,tag:a/Il3reURp0tkV5jbqC1sw==,type:str]
      namespace: ENC[AES256_GCM,data:/0GK8zSX4A==,iv:EbdqmnXxBU3L5lPhEWvGMWcmovmXeHsbRjQjTu0bxWA=,tag:gja0flykOjXJFcuIfjlydg==,type:str]
    redirectURL: ENC[AES256_GCM,data:jvSwA4E4sbGhLHs5CA22mIsKnpCkVTz1R1eHUwRHTJ5Ko85V67B1YJV3qWO4FTy7Trm5Z0QAOA==,iv:ENpOyXs7PVsa6+hT0t1rZicFmEr2dQg1pZXEtz+8ft0=,tag:ZQE/D58+QxAOIF2rbbRBAQ==,type:str]
    logoutPath: ENC[AES256_GCM,data:gjXps2IX9g==,iv:ppeiaBMrVnNOu3jM7WZbNWYL8CEH9s48v6H8OdVdJfw=,tag:VErMcEWXqzpfQyB8SUbJAA==,type:str]
    cookieDomain: ENC[AES256_GCM,data:jqU48+bjSjyilReWz8ilpg==,iv:a7bK6J3dPjwJ35ANeBkDI7cU/wmiBRTh3OnC7z2LCF8=,tag:nXC0qyD9k7qb4Rmy2+pthg==,type:str]
    cookieNames:
      accessToken: ENC[AES256_GCM,data:oIoW0VPWq2OZuek=,iv:IE3G0pJDL8px1eDE1XvDGJXS3/Xg4sJdZ/m6YOHA9O4=,tag:5qJXK369LZ644KTi4CNS4w==,type:str]
      idToken: ENC[AES256_GCM,data:vAIRUG/IQg==,iv:vqwxuXCTjGzNsu1ezSD5bi6znC/CaOY1DvOdobyZkSA=,tag:h/DoWCAAWbE09KkEOvV8sw==,type:str]
    scopes:
      - ENC[AES256_GCM,data:g/lHSiFL,iv:C9dTgPeZvN8NuvCyTegTbpgyIFSxaUwXnEG9wuuXezg=,tag:XtBcZ+AVzcN1lJXzIiXS3A==,type:str]
      - ENC[AES256_GCM,data:FCfXnFY=,iv:LKHXCLGiEqlpleL4CI+1v2+AiImoCfhUXBawnsDrRSo=,tag:u+WSWmNImb3rrCiuCT+n9w==,type:str]
      - ENC[AES256_GCM,data:3cjG7ldu/g==,iv:rHEL+8QJuK0zxtdxvz/EfOMMFIR8TeYAh73/TEh2Kdo=,tag:xdJaDvcrVz7rwBlRpO1weQ==,type:str]
    logoutRedirectURL: ENC[AES256_GCM,data:eHXOAAJA1NcHCzZMF1UDH57r2TtnCXIXrIoGIwxKpS0Tc3feQkXRrqkGJfFOU3W+ji4=,iv:wZt90i1zeaBkNti3IVKcXBqu0FlT4E2DkXhSjqD0EdM=,tag:2ueRHl8CP6DypNhBqGas3Q==,type:str]
  jwt:
    providers:
      - name: ENC[AES256_GCM,data:dQI79gfu,iv:6s5iW/7+yDegdxcpCP7both+naD0m99Af77gzr5X0RA=,tag:+KBOkxG73RDcm/kh3ys+EA==,type:str]
        issuer: ENC[AES256_GCM,data:xfC224IhBrfCPteKWXWLPGOc9KUF2yzmmmiO,iv:Z5HGuXEZWYS0/1VYH8XFC6VkCPxmekYCDJQmTW8Kerc=,tag:QTpAALMzSfp5OFuQOw29Wg==,type:str]
        remoteJWKS:
          uri: ENC[AES256_GCM,data:XBshVVrbTCvBc5+g6YhQ9wFOzUGPe2ugXLEYg5T4M1r7RoLNIQXjW+Cj,iv:/JC3XSRC6R2AHY2DkqgyktbkompECQVsFwhoG5pQZ1I=,tag:gG6ibWWYWZwMEZsFyKK00Q==,type:str]
        extractFrom:
          cookies:
            - ENC[AES256_GCM,data:sY23Wf7Pkg==,iv:y2at9gZFA3t+LRZuGb2ONxOHN1W6Axx7tS3JWCsvOoo=,tag:O7Bnoj1zrvYU6J6kB5r5NQ==,type:str]
          headers:
            - name: ENC[AES256_GCM,data:AfHUzdLrtf04F+cqww==,iv:8fYkShyqZfLKQV7ZXi8g+aZWfkV5tHJdT9D+T7JiP74=,tag:0OXKDu2pA1dhuc0quvnZvw==,type:str]
              valuePrefix: ENC[AES256_GCM,data:A+Xx7MnzdA==,iv:2SFnJdDd0udqEav3dGSvtoQBjtHKyGn4XL52ZN7uiW0=,tag:4NubLHeconEn23XZS4O1Pg==,type:str]
          params:
            - ENC[AES256_GCM,data:BvE/nVYIxWKuILrf,iv:xeWyLCMyHoWj7gRuGi4/9efytY5uaARYHJP75AfP72A=,tag:dZ7un14qmGALCNUE7JI6bA==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:DFG93A==,iv:O/tmerfPgxJckQ4LOlrNhHrnWELza/vISh4IgvrqEc4=,tag:kS6uV1ICRJ9h4PAsB7Qasw==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:4GCuglVjLa877rgaCdYG,iv:iVNRhT51pTnZd6lwm0/zfaKG6BdFOeiscjYZ3plsjT0=,tag:abg/PjYJHBsFFcmwAqX0FA==,type:str]
        action: ENC[AES256_GCM,data:YGxPYOU=,iv:/dsIQBBrTuFkcobEtBbjyZKOYGrP3rLylassHQ9mEzM=,tag:af3/kfR6Hy65dwsQfIbPmQ==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:KxqUfUI8,iv:8Rg2z6pvDEbEWVESfX4fLjyGlCc4MysuAM3I6Kk1xPU=,tag:bKorzj3GTKhQttxBpF0Itw==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:lGXDDr8=,iv:SBzagFG20CZgPcevY3wukif104ULb/YhsK2UEhIjzmQ=,tag:/6H05URXEhXDFLcIPeqpsA==,type:str]
                values:
                  - ENC[AES256_GCM,data:oXfI2CkrxXumt4U2wCx6PA==,iv:jgXyQ9TYfmd4VRlnNEgZNw+l2djUo5aF4L2p1l+QWaQ=,tag:CJZrv4sPTt8I9WfNFs/KOQ==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVSt0ajhOcHB6Q2Y3LzZP
        Zm1obVRWV1g3VitMSFdDRzdqVlpjV1hmV0RFCjJWZXpnTzgwQUxwOGxZcUdWc2ty
        dnIwdi83OXFIUEtFbDFIRDFQRklMbXMKLS0tIDJkN25RTWpvNFlTS0pCTklRbGE3
        NklJVEdSL3BCbW5qQ2Z3SmIrQXNaczAKxCQ3AkSo/euRu5ylD1VpMzWc9XSVFsGJ
        NiPGt5X5qegpv4o0AUdQPedErtDCCsne6DblHz01TKtyOhrluvbaWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T06:02:59Z"
  mac: ENC[AES256_GCM,data:kTKZL4ECoje1KG3H+dj2vUELx5GXzKtO8VzCSuJOzlnDDYlzZdORfwI64oABnJ//zmrNprdpoxso3PiY6NYHqyVbsAkJX1724mkSwNEg3OvgVJ8U46yJL7BXlbrRx5iXYUlmah1PKaYywF5IUse9IVO1uKy4CbvA6e2ZaoSrMp4=,iv:WcHgXYx2/Fo0zTEozjbVYm6FEaGvJrb2OUfRaVPcvIo=,tag:4p5gjABydaE5iJxOm11I2w==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
