apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-internal-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:DoTUN+sW+n7AStFWm3ZhRl3cGLdBN/9smA==,iv:Jjjok9jV3gf8j72ZLUk8COnqwtdMmPlU1rk92MMJ4Ro=,tag:1IkRNWY40GmvbKEMBemRyA==,type:str]
      kind: ENC[AES256_GCM,data:WFirck2vpw==,iv:Yw70ODqJYbm01XLdpVYJR65fp0AFaUr/ODcGsT/nR5g=,tag:X/x3/WpgFpKakmCRGMa5hA==,type:str]
      name: ENC[AES256_GCM,data:gElpTPKJuxh+nP77NTZzdG8yfOA=,iv:ugGTmgElj8/6DVGIqXUqDPi23LF8cld2k+N+LL///iA=,tag:2Yu7bVsXOrtsQ9DvEfx4eA==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:tU0FUHzy3hozthoVDrX5vl9AE+u0y1RidsCo,iv:B+e+QjBkOdH/8qjBSliSdW5O1xZRGQm7xrTaRSC9Ebs=,tag:4m+J4FFSW/cBZgZZDdLVlg==,type:str]
    clientID: ENC[AES256_GCM,data:BBlbuX5ilizxHJcuM9Du2t6hkiVnrqmOcm0AMqrjMadGX5M1oWvIxLcOPw==,iv:gKQgYcVb2l69KeDdny4kZ422TNE+TAHEop3EXseWty8=,tag:vF8BQh/iLQCQQlzj+Gyiyw==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:7AR+jidnIWz5X93eSs3ChSD3CLrALxEVYB8=,iv:8WhoqFhco+cW3DW2b/bmbRg7aH+6uSLAH4eyGu/Pe04=,tag:IVM0gsGs7AkxnCuFTfdjRA==,type:str]
      namespace: ENC[AES256_GCM,data:BZcvKvFZnA==,iv:Yx3nUx9owC8LlEjqoySnGYF+tdF+LrqmpBwAkPbyvTw=,tag:1SQaagttTniZC7KfsoqEfQ==,type:str]
    redirectURL: ENC[AES256_GCM,data:vV1IjuApg6qURG6Llks4x2C6/BKMSKU2QNjJJaXKa4Ii+lzk3ECpnKSMoFzjXK8Fasrduq91Dw==,iv:ec1egkEzTyYhnpjmsitL0onS/ODwMJOdgJrpNHlniq4=,tag:NvC7BBFEm5XJbqVozTUVXw==,type:str]
    logoutPath: ENC[AES256_GCM,data:mMcAVbNlWw==,iv:MXKzjRY1OHpjpWJRAO5qAOTvmCSYX0uvTMBYt6iUjmM=,tag:33cSsGB9aHBzeyZ2zGoXUA==,type:str]
    cookieDomain: ENC[AES256_GCM,data:UidAsGkLdf6DzOF16RqOSg==,iv:/jdXhlHPQfUrEYtgzpGVm8sZrnWISJSlgMwpEQNT8jA=,tag:yTRVY4usZwgjt8FKZQYcdw==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:V5Pccw==,iv:mlfLEiJdGbvpYgStJAI/Q4GxS9GjEYtHFaYCcInCGz4=,tag:5OD8aoRnrcLSNiifWaYh4w==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:N9jwhi21vvpUjkngT19+,iv:jKoRWovJW46N4e7mM0udnnCTDl6yOpDW2oU11Jd36uE=,tag:f1b3RkmpRXNdpYSepDMqqg==,type:str]
        action: ENC[AES256_GCM,data:gB16tEQ=,iv:XNsIXjMlrkyI75S+DikZvU0rspu31gw3ZPtBCHdaB1Y=,tag:sezNfhXEjYvcEqvQWGaeIA==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:fHWXWQvm,iv:143OTtW0o7u9KtwuM9LFlDOJgNXN1+zxqv2u37G0fqE=,tag:jdnzj/sWFNLi0fM1HZZfpQ==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:wsG3BnH7/j5r1syKOgk=,iv:h5JLsuxJKNaJkfH6Wx5AEqZXxtMVXPhVkzb1/duywlU=,tag:4esWlj9zdEuOkW0DePx7EA==,type:str]
                values:
                  - ENC[AES256_GCM,data:t3QYnQ==,iv:gdjZTyojpb5YnR4r8gGxtB0SN3+wCL9UekbeUE6Boas=,tag:fGhyNYKl5qw5THqUHWXUgA==,type:str]
              - name: ENC[AES256_GCM,data:W/0OMHo=,iv:LTig0a15yXYRA7XWwJ4MCTYgwR4ExD1wFKBecwyCb20=,tag:xpJKzHkl2NLqAJnTipE6vQ==,type:str]
                values:
                  - ENC[AES256_GCM,data:cXYvRH52szUXZ7jlkM8qK+ajizVihR62BlzLGEIwf3U=,iv:ZGdzsopM9VuV8C0XLkASm7AjqYY5LgyLT/Qn5I0ifVw=,tag:SRniQLaEB6Rj7uGBQBNpCw==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cm56d3EwU0FiaTlyRnZ2
        aUxoM0dGdVJaNjFsUmV4UXRaWDBFQjF4UUZFClAwTWpPUU1qYXl0TkpvYUZpQWNN
        eVZDM296T2drNyt6c2p3TWVia0EyRGsKLS0tICtwUE1CTlQ2YzJYcFBFNkN4K1hP
        OUpSc0FzSm9kUEdMbEViRGZvV3hJbXcKve+SHe3xtz6rNXM/aF5da9j/WeZBHLnN
        MI0D3zWukuyM2j+86YvTUfdQowT8SnO+0xEwsdEFJR/yxbCTu6r8ig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T06:24:46Z"
  mac: ENC[AES256_GCM,data:rdpio4St6h16lssatYZd+e8/USJU+buSEnA6E/eGkZzo93ZWpAIL+OHN5qU0d7XHFaQwm+kVrsop+kYjUOZJKHs837gZROCHreNcMK+OMvAB2tfVeyFvbLQC9FKJ//jWVC0l7/m1Yma4uor6161vfk2nTL5hoFy/Cur2x+1dXTw=,iv:KZnpjwMnSGG2onrAQ1eP5NlwsHjI2kfQj9onR2GkL0E=,tag:GmzHyIt1axDGouN3d90/iQ==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
