apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:QStcc8nwBN5ti9wIS9Oc2zw0RdNybLrDMw==,iv:lfD5rOavAZWas9vWt1oAuBOrNhqpov6jcrbUaJu2nu0=,tag:bgNUq8loeuKEMxbb5vo31Q==,type:str]
      kind: ENC[AES256_GCM,data:319k3bY4Lg==,iv:Rfvz1eqYdqdoPTPyAhj5nktkud8s+TBbHljE9aroiHs=,tag:QyTG/Le2WFPwIiim7z5J+g==,type:str]
      name: ENC[AES256_GCM,data:VLhx+mwzncGYEzM=,iv:NOt9WD1H9IutjJNiIJVQ8Cp8GxGf1h3LZrn4jw5Xc3A=,tag:P+HUdPFl6sJYlpkmtx7H7Q==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:idBYYqGMwnehMkH06rmLwsByUCAjRJcT+DaA,iv:ZjYcynjmaXddgg2r1zBcpidZervSLdrIvfgfKcOmEXY=,tag:UXdB2ZzTw60BejS3keRE+Q==,type:str]
    clientID: ENC[AES256_GCM,data:zquItCRkSmjLIDkELHpF+1bRlsZt/XRDliDIFHcTZdkSg7mOsqr4R7nv61bbOtsspDF+h+c/WXGbQZqM+gyJH0V+WetgsTYw,iv:VoVOxhlhyK/HynQgvn46I2CPIxylF5qie3iDknwOadM=,tag:i4qugKEkx2NuxnfCifNNbg==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:ycai7TFqUIZGvM6ayJcmx2zhukzdINyz5Es=,iv:DL1kuEh7d5q5N1p4OXcZJREp0PksYApDifyQ9n8L984=,tag:NHM8/oscJyRLEWuuK1HuQQ==,type:str]
      namespace: ENC[AES256_GCM,data:Bdosb89JJQ==,iv:GqO8Bem0th8sr15fo41YEX5nOsvsC8xHTuG1Rqt9JRc=,tag:J93MC1vmF64Y7XttpGFOAQ==,type:str]
    redirectURL: ENC[AES256_GCM,data:SUXbQ+SCJS9WXmZgErj/V8Q19WWXL1GP5cApWqMVpiSfXlulM64prijrLA1Jhw==,iv:vpzVGWWC9Yh+KcY8TeSYFB3xwhrgp0hJzmGBgE58WKc=,tag:GJbrDOZZY4+BH7W7bxaFtw==,type:str]
    logoutPath: ENC[AES256_GCM,data:ZegWzYjlpA==,iv:Q1R8XZxCyXLv1N5NOQHUn0AuWw66Lkms90EM9e+aHqM=,tag:EM2QYOzNY8THZjQdTb1mrg==,type:str]
    cookieDomain: ENC[AES256_GCM,data:7X84KuQds6sC3Ynms9vkBw==,iv:pYKigfPWzH3YOeGzwgRxzdDyFlY9etmDePBfw2Sl02w=,tag:s+0EWcbZOcgcFOv20B3lOQ==,type:str]
    cookieNames:
      accessToken: ENC[AES256_GCM,data:L+kz+vcA9zLyQ9c=,iv:SrBK0sQ8kH66AKLUzh9hJv56dm3fC/QdZDYq340A+Fw=,tag:fEyGZGSyPzvztBA6b3utng==,type:str]
      idToken: ENC[AES256_GCM,data:NvyZ0El6Og==,iv:jP+P6NR/AcYXAMfcpOb5pJ90MeRH0+3NQHGxrDavS5E=,tag:8PnQs55O3R5e3XeVuRjc/Q==,type:str]
    scopes:
      - ENC[AES256_GCM,data:SR3N9eKE,iv:gJc7DelWyV77k/2taT8EQmsvDe+WOTXP0lqHr741Reo=,tag:G3scSIW6pqjMGo668cInDg==,type:str]
      - ENC[AES256_GCM,data:tVYUf3I=,iv:U5zzXtPrHUOp45v+FHjPURxbBPH5padsJDDVkUdlaJM=,tag:+UWdjk8jVZVVpOr3N3H0hQ==,type:str]
      - ENC[AES256_GCM,data:78RUz6cUdw==,iv:lWK/BlRAvlPp6Qv8VxUHuWX+gUNGPGyZ1/uZEBxm2i8=,tag:I7DB+11GSnfMSjeO7F24ZA==,type:str]
  jwt:
    providers:
      - name: ENC[AES256_GCM,data:36AePY26,iv:tKM6GKST4j5n2ghPWCqY35sKUqsYd0VU1hKtEp7qacY=,tag:r8rwDgI1q5dLD0j0aL9gsw==,type:str]
        issuer: ENC[AES256_GCM,data:B36N5fGaVnA//bfC4x/DFl/UDnjxRwtaamdG,iv:G8AhpwTVyVAb+1WFGztjDLqNguSpIVNFZlEpcptx0Xs=,tag:gE0kirT+xNoM8JCBqSH+fw==,type:str]
        remoteJWKS:
          uri: ENC[AES256_GCM,data:MTfJDlryk/wtIvCO0TA+nht8dxaFVehVk2808NYUNmLc/KRhxPg1iHMc,iv:3vbw+bx2RKucS4jWeAeACwTUET/X0YBFeHs+hGYvVqs=,tag:YTuJP6pWLJg2mHjrvpqw4w==,type:str]
        extractFrom:
          cookies:
            - ENC[AES256_GCM,data:BmUhZS9hnw==,iv:XgzGVkq81KhKiFCS8llhh9TyMbe5EWmvaCfSbjv+690=,tag:+O+2kLDBXXDBtE/xrkbqaA==,type:str]
          headers:
            - name: ENC[AES256_GCM,data:TuVmcPt7QvP8n+357A==,iv:oRJGZSoSojuNxTTqoebryKwPksTpcbgcJC1yMZYk6hk=,tag:LZmzsUwODCk4slKq+Z91mA==,type:str]
              valuePrefix: ENC[AES256_GCM,data:h2bGo+moeg==,iv:PdwVtnlf+1W4Y308VR/jxvkDyDMW5uF5sC/PkI955iY=,tag:xtJerCvpzFyJjIxom0jGPw==,type:str]
          params:
            - ENC[AES256_GCM,data:I7ulzpdevh8N0/rI,iv:HSA5pH/FoUzohkwQwNLevGXPHHJBcG+kb4e81T1FaJI=,tag:xGFlVYnaA3KRevhOsHscCw==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:ZmMwCg==,iv:xUm74Nj2hTMDwaChPFrAZgrHtyzmgoJCrH0cmMYQMSU=,tag:D0pTrkWmfWy9eA7Ssv2PYA==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:YZhjgdD0zbX7eCbccIEw,iv:IU2t/DvWll6o5ZeFsJsJBhdk+63ThVPagUsOlndZC2Y=,tag:DE/yDFiRXsO+yPNeLsC1WQ==,type:str]
        action: ENC[AES256_GCM,data:WBCdyZs=,iv:U+ja9tsBbxTWZNx8xHIEDv+7Z9rE+UiXrVt4LF934tI=,tag:8diO3nKElQ7ELFjIyh1BpA==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:MoYkHzdG,iv:cY0ch0NQ4ChpaFoGHMbNcJPSsvyWY8rmKJzLk9Zf2cQ=,tag:fhbmK8F2RGOiPl98g6N4rQ==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:fgeE8z8=,iv:lIfpR6VXu2fCaM7ZWr6NM6LSyT+lt1MtsVXM0mQDZ1M=,tag:5h6q3LAc3t8kI47faM7Fww==,type:str]
                values:
                  - ENC[AES256_GCM,data:8mmN1C2Ww8z1EvFeQ84wyg==,iv:34/OuY2Sg1M+39Lvyhl1CXkSdNPxFdZ7zClivI0CDWw=,tag:5bP6rOEfQ8QfMOWpsqWyzw==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN3ZPeVlPUGtLcGQ1QzRX
        dEFYQ3UrczJ6aFVNN3pKS01yQW55VVR4djBvCkhLdmpicnBRMnl1dEpISTlPMUg0
        K2U1dDNtcnNqc3lkSjBabXYvYkN5K2cKLS0tIC95TkpvU0hoL0RIcitTRlMyUW9K
        cE5uMjhVZ25DV01WdnMzVWlRQlRPMFEK+GrmU48CwtAZTJ2kzoBPXHSg8Noeoj7V
        DhoCegK37kJh24t3Qozhs8BKCyLBJvmsLZJvu+F+Kh+DoI6Vt8Ch/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T06:04:09Z"
  mac: ENC[AES256_GCM,data:260nYzbRV7EkgK37jmqA9bm91tEdocrhw0s1eJBjMFajik/f8vJP4po2MQt/tIF9qmXMIMyIfXg77S1cY/2/rarKEwRvY1qBt/6dnfjE6oyeZzXQckMG9PXeIGiGrFoSRUh0oLM/XBZmAqbhUvs7NrdZ/NjG6oPVXpfaJP2E8tk=,iv:OuGEcrLO3Cl/R0M7yOXrzKYjKLFoqhfzcKn7M8zVyq8=,tag:gfN1we/InXvy7kAdp2T1nA==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
