apiVersion: ENC[AES256_GCM,data:h+gRxVkeOCKzFueqY3HQT0HNR5oNzuVFEnkJm2hF,iv:pqIOglwDlrqLXUYIuzoQsPhivRnNpfruBfnf6GwumA4=,tag:UJD83uouZiMAzhaKZ+YYGw==,type:str]
kind: ENC[AES256_GCM,data:qSsxBan6wi+EF9Nhd+o=,iv:ukJ30r4EzW2gEsaU63FezpenPh2GTkDjLay67l8UnZw=,tag:MlkoFYBAbWgz1ka5VXZIvw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:IJLdR9/c995xAZgrocIzKqwMeGuiCAO3zqO1,iv:gSVClObpY0tGXv3BohddQ2aZSTmof+ylT7cvTRwI5Vc=,tag:AoCkCRTU5NiSO5A1WhmwzA==,type:str]
  namespace: ENC[AES256_GCM,data:YOtNPgLLVw==,iv:A4ogOoCulRZ5NPDn8BbcvobW9A7iqK5wVKKvf6dzh90=,tag:yhuMvqpXDhg1mY0qPMIZxw==,type:str]
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:tNEQfhz7wHbwtzmKUK1Z+Y/Bshc4qVn9Tw==,iv:ybQXArqzw0pbOrcfMBdxUnFYlfP9vpgGfBYfs1ZPDp8=,tag:nmKNRffufd1DVrvtkPovYg==,type:str]
      kind: ENC[AES256_GCM,data:nHAIGetLrw==,iv:QHPF5JNTPHzPB2GPEil0h/xs8u5QvlWloph+Xzjs0mU=,tag:XFh6qqnoMGtstW6N/HfGdg==,type:str]
      name: ENC[AES256_GCM,data:1KJ6t6GdMcHDyld3gTDKCH6bBg0=,iv:x1J2ZNm82PX+Z2C8Pv+9oMx1/ZfLoGKMD4zHXiKYOac=,tag:HAiP4xMXp4bzzmYbAdya3Q==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:I94mUG4zZNdC9sMkVqp6NctIpjDRT7KeS2Hw,iv:2NPCg2jubT/sphOAoNZvGP+IcXszQxco8kFp8UhLUTk=,tag:uhE19SOj+2DVPaeyo4njEw==,type:str]
    clientID: ENC[AES256_GCM,data:n5ZuUPhIUyBRehW6EpGBZtoCCkqBc6PqPwcU3jsCsBqNmicrCE+h4JLVqQ==,iv:Gvjnt5MtPlR2cW4S/HsAU9dAgoSVKCC1CtWnLW48ShM=,tag:xk95cTdqPo+JE3SryMHJFg==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:pxT1v7RCpg+RNo30Y2tiD+SDbMku2MlS3YY=,iv:L+0xzffegn6vAAwLcEzpZH4iwl8ju+guw26AKdY88dc=,tag:wcnytUrpt6BX6VihQXgtuw==,type:str]
      namespace: ENC[AES256_GCM,data:yYWN00GC1g==,iv:D8TAuBMDVQlpCBbtHf43+PiJOMuewJ3gsAftI+x3nMc=,tag:k7zLJTzQ0CzxjipswTuqjQ==,type:str]
    redirectURL: ENC[AES256_GCM,data:BsDetnD9ppyFcMZU23dUyL9FsgpuT9mlQOiJabaPCmys9Ef3rYwkPL6L5abiJiuzHFGM5n08MQ==,iv:BiGOCHysOKEsdppsukKYShfY0c7aQiMgeJHeaNenwxs=,tag:PGUQgb9DK5IMefm9i8GMdg==,type:str]
    logoutPath: ENC[AES256_GCM,data:KB0031zMhw==,iv:Xfk7n+3dBcaxgHF8n2dkvVMLI3W/Q9GXync7/OQHYHg=,tag:72RyB0ull0y3RinU/Iu44w==,type:str]
    logoutRedirectURL: ENC[AES256_GCM,data:w3EPSslfwwaaPXW9cJFAac0sxQtp9YiFOZy4bu6M81+cmMTwEGWMtHLC0IcPu333rvE=,iv:YfmB0StTUwVG+bDHXGYuQmOlIYgBDexzxMG5ZmBvfEE=,tag:OcUEVc5uuaktVJdvL7drtQ==,type:str]
    cookieDomain: ENC[AES256_GCM,data:1hP+IVyQ73Mm7khI0WOKWg==,iv:JoTnCGc/aAHCsxoC6EbT6L3QT0m8VDNla+SQgagHGfY=,tag:fo9jt/sPHMyaSivW2IlhIQ==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:XfOPPg==,iv:lbWf6JYyxxL7BcIyCJyAYLt1Ozz8Dd4ieulemvosxbs=,tag:sJ2q9Kws+8on13elZrZsXQ==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:uSTmuu6pyU/nEgtGMhEE,iv:qAOBNi1JZvxjsUCjM5h2D5T3FoJFrJbsgC5CS+0AAIQ=,tag:wpUPjsfSXukuGEesrNopXQ==,type:str]
        action: ENC[AES256_GCM,data:DgxuX6U=,iv:XntjUmVKWVC6LiET1hkBjLMXZpNqJ1RWuRsCB7LxbyM=,tag:pl6NhdSUhjU6EOcb08UZAg==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:Zx+u34nu,iv:X3F5hZaTFZNiQM5MttJ/QHrwIaRgm+WiU04KEjq3Bn0=,tag:JZniImh3BylBOXBsfrlF1g==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:LMS4xbwkOV0rvkERy28=,iv:oVqN8Ft86WXwR42wM02BZ4saAw685pvn/vaN0Hs6IdU=,tag:eRqwlOxaXjr+qVGwDBtg7g==,type:str]
                values:
                  - ENC[AES256_GCM,data:FD4Itg==,iv:dD9X08vxDzrU5WfliFFURKNEYFb0B2s3+SKI3bt+M8c=,tag:yfOvfKx6Qi/FTLnSmSDq8A==,type:str]
              - name: ENC[AES256_GCM,data:ar7t0rk=,iv:dOgv0ttqHAnUqDCM6MxU5B4+/TH6lRHctAX/AZycv6Q=,tag:+JgEACdmZCaiKOujLAtA6g==,type:str]
                values:
                  - ENC[AES256_GCM,data:7WDRBExZK9iona97tt+M74xy98z2lls=,iv:LcdDOF0PMuiYv88ZZE3oYi4HAtedCOYwyECLyQREWB4=,tag:lnRsQeiG5RIRMtVC/sIifw==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSkxMWU4wdDQzRkY1VWp5
        VXVJUHZzMEVTQmVweUtnaGxNalZUcVZobVdVCmVjNnJTNnNSaFB4ZDE3OWF4bkRu
        SnFPeGRRNHVKa013cWVrOEk2VTdTV2cKLS0tIG0rSDNySlNjRDVxRFFCVVVNR2RQ
        WVJTdVFxS2h0UzdnMlJrMnQ3QUJDK3MKEGZ1hY+14m9geyQEjFSxsjnVv2Zfje5G
        6BKy/gkJROXwv0B0UmOywnPiogrAUAb3wjVlaL83Xbvaj70qHSXevw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T06:01:55Z"
  mac: ENC[AES256_GCM,data:Kl6aqMRkw6sMvfPx6sQa5TUQqe5UiSnHn9ijpgOVSs7pHyw7lNkh5jy8/ckTowiWo+4lp5IPhFDT8aKGTGjEFZUH69D8N+REHmK5HSBIUARVbDgQ7Xi/RB2W0iS1GL/oxc1ALMbeO1PgkXnKgUqvEZKP3lHqH5Bn61vZfRIMFWk=,iv:83RDm+dGWiZ88i4JOCJNNlwT7ek2gjSwNkOtHHwlC5Y=,tag:O2SDCo9DaVjfzIXJ5Mlrjw==,type:str]
  unencrypted_suffix: _unencrypted
  mac_only_encrypted: true
  version: 3.11.0
