apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-external-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:sZ3KEhjwWQhjjqaJNlBl6ZMLWYFW54SWxg==,iv:vymD4LRr76UGcdnmvnALomuS6TfR9cusCixADzWWi2o=,tag:H28NipefMVHIwKilFxqJOw==,type:str]
      kind: ENC[AES256_GCM,data:lFHuq3iy8g==,iv:0I1ds3GDLDQNGIHSms3HziDaysCOelURA85aN2fv638=,tag:MSp3D8st9tLwrFxVyULfkQ==,type:str]
      name: ENC[AES256_GCM,data:NtcjOvX3AgD+07VkFiK8/f/Hiz0=,iv:iuZ1lhW8Epd3vAvwFMtqaJacyMOllASJITcfRWnpjp8=,tag:/eDKrTP4e8yAHAWDEAmsew==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:KPMyzASnxR7qoEouUuefj8pBTAoKnQ+mdOBf,iv:2va+aHAHVVthd+qVqcNxOAIFVJIkN1ghnYY3USLtk2s=,tag:TAPT/tY38QBoRwy4KGuKTg==,type:str]
    clientID: ENC[AES256_GCM,data:/hBuInYLid/nchAvr5WsDuh1a8hSVkMDNgpzwoTLBQIeDr7vyIzv5qEURw==,iv:MFySfclvrC4XPo2xBc3BMyo7g2ptvj7N4xD8uC09Yxw=,tag:oujzKZfIDuBBKLYRpGTkNw==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:a29t0SBgYdWhryv+94HgmEFpqd2/omLWXWM=,iv:5x0xA3gMC1CyN5Yn7Q5W6Y0u9KDaU1fJkCdsW1zWT6U=,tag:EFaSQp34XIvI/2x1Y+S3mQ==,type:str]
      namespace: ENC[AES256_GCM,data:OsMxj4Xs6Q==,iv:aIGLZSpzNzdPTG56v6eAq28ON/6mFqTgFThTF1rOFz0=,tag:0ER8YcWO7zh6eP7VREzDlA==,type:str]
    redirectURL: ENC[AES256_GCM,data:r3q9VRjj7/yQSUds2rGkZeD/WCK2Q3kDv9s4RbNpvc1dEpPJ/QOoIwQiDDQxoQsc+Rm/tR3fqQ==,iv:IUp0mSMH16d51OzYl/nywqk7HjSlurJQp3N/vhFA+zs=,tag:oLzXu3lF1oI73iYhjoMlag==,type:str]
    logoutPath: ENC[AES256_GCM,data:7GZUuqe8SQ==,iv:Mw//bPj1Ef/FVV8OCnXoe2WhXV28SsSitVlLEMBCciQ=,tag:N8ajx0GQQAD2aDQkCg3TzQ==,type:str]
    logoutRedirectURL: ENC[AES256_GCM,data:zAWDVtzvU2uzWG8P0X09nnxC0aA1tce1HfG+x1MqknFNiA9liuS7IH5m1xqy8Ufh++k=,iv:2X2f/YG38L4pQVup9cqi+BdCMsN7WEi0jsxsQ3vI+Fw=,tag:snKik+WkBMvZxeO1gKZY3w==,type:str]
    cookieDomain: ENC[AES256_GCM,data:gSi/Bpd9G92Ln0Rx1hKp9g==,iv:w/EhlIne05jaZiJlw3C5DpFwk5P1rJ1KYAr6E8UouN0=,tag:mcSjhb+sbbvfk0dvuVsrbg==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:nikkPQ==,iv:p7AfeF95+qU25/+fc9DsstPQjS8H+54tk1NobPKO8WQ=,tag:zmuSpYznvHwL7Gd6qfNFcA==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:20A8GsiO3PmxhdmrvhIu,iv:ExtTa0HaovPXejVRnFWMvIE/ECMo2kQQhQoh2Zz/BIQ=,tag:sM11/HaSdB+6Ve54ivbxKA==,type:str]
        action: ENC[AES256_GCM,data:f8FfCZE=,iv:rPfzkDQ/b0cXFuVCBscYOKZwwX6X2TMBj9EB2ZnAuik=,tag:PgnGwELq3FCM7KPexStyLg==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:OIDCFAVw,iv:XQpFolJQuiMDuut/YnieSVQ+A9zW7ijE1HonSleT4U4=,tag:kXEozkYfcHrJijLEvxt15A==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:l3q/nOqdhMNYxUY0L8o=,iv:tWxASAxB+Y5ewljDogWddemrDS6ouT9K/DoKZ88KNRk=,tag:18oVMNr1Ghzhznhw8NIQbw==,type:str]
                values:
                  - ENC[AES256_GCM,data:FkVN4Q==,iv:iHBph8Tc0dKG+UCtunAbJa/Ze3WAbWbqmTafZjbR6yY=,tag:65L/yqbJ3E4xPWW7uXomhQ==,type:str]
              - name: ENC[AES256_GCM,data:ko0e2Os=,iv:fMCyDFosnRs1+JxGMS/2ulsDhTk/R7E7hTLZuOOxA2A=,tag:IEHZRTDe3gCb+2J+3UohJg==,type:str]
                values:
                  - ENC[AES256_GCM,data:rOcNn5OXdSd2+6b73FXva/h9mNpLT0A=,iv:JXRVo58BQzWWqrg/+2WcApN+24h+T9PSrbfK1L9EuWE=,tag:NNY3FcpDfsdFNPMZjj3w5w==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTHpUSnBmWkgrT0xjcG1L
        SzMzbGM0bU13STRTVEVyVUhwaWp5VlNVNWpvCkdRbkE0aXB1ODFkM1preTlNL0ZF
        cEJWTklFSlNYVjFaVmJjTVl3NWJIckkKLS0tIFAyWVh0NUdVYmtFWFBkVDc4OVZu
        V1VWbUxDUGhlOFBORVdYZ0JLUWxXVGMKf+nLj3VCqH5lzaXZFz8crYUMcNwWBLN7
        IRXgLTGFIl7rW7gywPr0sFGYqFlyKOIovMQQ0gOuXZ9SLzhkX3rZ6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T06:19:58Z"
  mac: ENC[AES256_GCM,data:Cdvz5VfGwz2gwk5vlMJr2h/o+cuuWVwhbST8wOS0R8K74p5uzInwJ4lHYvmhvzGcfYdyhnYxcD/K+dDD3l0ljTSCZMIDp59uA1Q/+VlAWqzi3oHqZV7wlNe1UkuW+Oq/v3xz1pWZVVaxzPbB3TaWZiaOlVVLyisvwZYMDEdgkh8=,iv:GXhUgg5rYqWjl7iv5HCrGw7fy23iLlQOGOqX14jlUfE=,tag:NskVqQ7N9pDFg6jIVgWfCQ==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
