apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-internal-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:AUn42uMDx6A4sPPkKKXlrt2C2Mb+NTQkzA==,iv:fXzuOnwndc+sSI9j0mF9kQ/WiRx7nk+BKFJf9bkrFJY=,tag:o74x5D/FQC7ZWPQ4yoa60A==,type:str]
      kind: ENC[AES256_GCM,data:VzsuHl4mcg==,iv:5uwAGoFrJSdwD6hw7SsZ1j++4GJyME7unXZceZ+bI7I=,tag:yCn/A3dojUE+uHuCUbnM7g==,type:str]
      name: ENC[AES256_GCM,data:A7VyYGKUzG1z4BGwVXSPDTOsdw8=,iv:IWV39YPWTVzEHcs8WJ1kOaKXsSKJk0tsTBKEN4hfEwg=,tag:tNsHgPzA8CN7R99JhxBh7g==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:WEzaOz0hMicAY+tEuy5tARAsKZuG1i4zdPNP,iv:3uTObdXKqMJYtzVJZC38mURJO9T63FTnd/mplmT+IsA=,tag:y8JybtCrZowjITiA1yZS5Q==,type:str]
    clientID: ENC[AES256_GCM,data:qkpZuVvF9EB+lkD957d4J9DosDZK36gQCbWjFZ1//oQVVEJveAk9Ri/P+g==,iv:jzQO2H/3CcrKV5QYyXrFfKyLGLEab5eFgYsHIWaZAns=,tag:QIfyyd/DQRjn0Y7cgFgNVQ==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:T225Nt62hcTd5VNV7meTs3kD3o75VkB0ccM=,iv:b4jr/D9qRQhuQvX7gJyAsSufqLQVGndfJ04YBuvQqKM=,tag:SEQtwsuxVGmxmD2D6ublZQ==,type:str]
      namespace: ENC[AES256_GCM,data:bGxwxkkBWA==,iv:etc+TubK6573DX7ucdKsiyWotyve2ho72QcM5eiojsg=,tag:IrjxTfcNoCL+l3GajrP22A==,type:str]
    redirectURL: ENC[AES256_GCM,data:JFMFd+qUYyRO8XRtP2V4PDzXA9QwqUxp6+iJ2Eha4Koo7ZWA2+yKPI0SDfV1z2BLbOFOlY2Ikg==,iv:tP/YtjWAUCLClAeth0T+EAMnsUcYlj9ozHc5BrJSXzo=,tag:NxwD0PKoGR9fQhtMxsY3EQ==,type:str]
    logoutPath: ENC[AES256_GCM,data:73ZozB+RiQ==,iv:O8QHaZS2tUEzZZTA4FE8Dss3r7E3culZJyk8rEmYZf0=,tag:qRgnxwezQXdiA6250NMb4Q==,type:str]
    logoutRedirectURL: ENC[AES256_GCM,data:nqwV6DnSmGvtUgY7L0dYdybe5u8dVgtIoSaTuAY2WJYIhLKcuU61mv2MYdV8NbfBxPk=,iv:8+S0oWiMX39MknUDAa9IQ8S1cHm20iR5G8cdThV6DB8=,tag:lCCQFc4Pkk0L2D7H4PWRmg==,type:str]
    cookieDomain: ENC[AES256_GCM,data:JRyTb9MkkLlFKpEV8RUlyg==,iv:yCPRpKI4BBGh0d6LqyO8P/hTI7Qh25uaWV+F3TX0yD4=,tag:upJK34pl0jWksHc6oTUlLg==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:Na4iHA==,iv:irhn3aMXBKXUe2FXnhVwNWvSrzRdOXwfX2x8dZMEALc=,tag:FrzI1D9b8fecwCVHcjlQHQ==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:ycZ84ykW+pWHdWG6LZIT,iv:wdTNfBUSd4E+QnBHgd8AtlGnt55R1OKqfLsYCNfxM3c=,tag:hhJxxvPUkoFRTMaqHbK6WQ==,type:str]
        action: ENC[AES256_GCM,data:80cgJdo=,iv:rjmjTmPVA6d1iHoYdXZLEV3HQXj4OPhyEAaB/5QFlek=,tag:Pr41m5PBhCNIs2gLLM0Kcg==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:FfCn1eww,iv:ROF+x3U25soXqz6D2/EucJ/nX9Xya6mjmeqt1GQXs5w=,tag:oY0q0m/ADp+drqQrzcbzUw==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:Ou3wN5IvoANGyQHu958=,iv:yazLKczo94iSVBhfi2iVBSTIZrUWwrwNocHnitq8MUc=,tag:D5M+Bq/yxVSn6aCYUv446w==,type:str]
                values:
                  - ENC[AES256_GCM,data:C+RDxA==,iv:9tlvWFnaWQng2ukG4zVWKLRco95+JgcKvIlHRQkn/d0=,tag:rnVd60+hhfbZLdj51n9djw==,type:str]
              - name: ENC[AES256_GCM,data:MyqJtns=,iv:GLn+HS+9brS7N4Hm5uRmHn8rgOCACHqC2ANFrp1TSX0=,tag:qvOU6AphTclgeXr8ncbBJw==,type:str]
                values:
                  - ENC[AES256_GCM,data:4Hj0xHDv4pmDj2pnHfEOujy1D4ySu44EZ802rgawOR0=,iv:QIGvo/ARzlmeQsL90iqrCcHQwAVe9apaTg9rEtwRH4Q=,tag:cho4NQIzyz+zJ9fTzXb3Xg==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGenlFYXZ6RWkrN2phV3Jt
        Q2NxQWFadzVrcXVwT0lDQXE2cSsrK3RhTUNZCjN0NTgydWJhTXM3YjJzQVMxSzJy
        NFdNRjQxaXpUTzdzMEVFWUNPalh6eXMKLS0tIHJkMkJyYmVyT2t6aHlsMlE4cURl
        U3JUZHRWZGZ4emZyRGVxdmN4UUFPc00KBPlB+4uJyFuhIunm/tJGIvru79nT1pwz
        hPKfpXMRbeNTH7cI9SDjtuR9Hy5ZwoBainpxhMPZd1CfLGCHo7FzUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T06:19:58Z"
  mac: ENC[AES256_GCM,data:Y4S8PT1nKD1QQf2xoojXeTMcsEnHGeelN8bPNl5jGWaP549sOA3RrL4EknlniibICsGkOF/xKUyg1zBwmBB3hKLMoTJyL8nWLhg++T4VTwhJW7bR6YTTufPxZv3qsvbaKNMCvZYSCaXNo2GfYluzKKTiLVhOCOMGxgwav/dcwg8=,iv:Q06F2ojfHIgv5XXO6lcYrYq+f7/K5TTPunHg5rABNi8=,tag:LM4qQsRqs+4ErSeEqzeh3Q==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
