apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-internal-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:zMjAyi2zfbjPYo36mTLQ+f/R/aOHtuLtmg==,iv:MjsZOMw37xJGikL6zslHgMR3/gQqLfMOFdRU33fhIHQ=,tag:sB2BYyo/EPz9yYguPLYK7Q==,type:str]
      kind: ENC[AES256_GCM,data:YJsQIS1D+Q==,iv:bBRuteG7wujfEayvOIQBzjmvWUi3JYixdBir6NJD6dc=,tag:z8mJ8P6TohLomc5aoH2m1Q==,type:str]
      name: ENC[AES256_GCM,data:Af3DNOZ3OkgO8hhBQgOxCxWbR2s=,iv:1cdZfdmCdkNCNFu/WUuXXW+c6xsYzYWyFUdFnWOxjSE=,tag:I1Jo42SLpkD029y/L9OcfQ==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:mpK9yj5VAKGjHtNEIlUHcXd4UXTd53/1qmnK,iv:0lr5PASnEAlYdkuV2DF/ExUCtWzZK66NDu2eWSWERrc=,tag:DtXsdPXKtL0wz95LoiN47w==,type:str]
    clientID: ENC[AES256_GCM,data:P0WzgqqfF6Iu9LITUfzY/Ly3xPNs9PgdMyXCK7KT+U4/Ccw+jBBkMrSidWoO/KdOPdz4XSvE1j3JN3KpHv1BVzUQ0W+cdLGR,iv:IYktWe4CUgmk3cWEXUBBmfCmTdrjXwWIrAmpqLvmCaA=,tag:8thiCpn0qkC/Ojw/QvljUg==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:/eI1d0/58CXDfrniX3WhnBzPQBwjSx89B2w=,iv:4r7kMdPzvNUVL0uiutdihURCzCSf+UuBcWWqW1MpPo8=,tag:1rwbg9xighZ5Rc40p3EdXA==,type:str]
      namespace: ENC[AES256_GCM,data:igarPSBEEg==,iv:EhjJZiZGPKuvwpo8dbW9ridi+m6ZpZaYoKDAbeje3v8=,tag:rbwT0Is1OE/i99z4xC2kZA==,type:str]
    redirectURL: ENC[AES256_GCM,data:zl6DiVQbdKl4jxg1UigsLK5Rfp7MRryUL6sRUpVC4V67vwHiNUu2L9K8NCGdD1SZm+XVkruMjg==,iv:HR0PT1L5ssTL0KFqE72LTqekPNsnF92sGW3EdUzvw1k=,tag:OX080w/X9yreWRqVA4CU4w==,type:str]
    logoutPath: ENC[AES256_GCM,data:zeKuIuI0Rw==,iv:rvuF2+BszPBCnrjZVNkPB45xgkAHyxeJtIQtnHao2kk=,tag:xDIrUAACk/hXsePvanlQ5g==,type:str]
    cookieDomain: ENC[AES256_GCM,data:AVuUXqNzzZ5U9kWZ1fDwbw==,iv:TC5xuzX44HpvQFZvtrmhHE1b/On/PNx7dKKIhhhF8S8=,tag:JQWzE1Gw2ZVc+axOCIRcyw==,type:str]
    cookieNames:
      accessToken: ENC[AES256_GCM,data:km6tBvfuvxF2Sm8=,iv:R3QAUb+gYyJR/gi4oR6gR6JwwA0d/7lTFpbmnT7CmxE=,tag:3DuvN/4VM01iO3x5bfgCNw==,type:str]
      idToken: ENC[AES256_GCM,data:o2oUAfRIoA==,iv:dPI/GMzf1ULeFEBUK5JiVIEZS90fYqHav+ODaasnjYY=,tag:zHw/o3e5bHDbitj2YQSv0w==,type:str]
    scopes:
      - ENC[AES256_GCM,data:k2njAv5B,iv:RE5YVZC0iyzLlITw3+L3PSEkwXbGRdrMFiPCY3XWMhg=,tag:cXC8zRM2M8nuGE9h77nxsw==,type:str]
      - ENC[AES256_GCM,data:M5v1y1s=,iv:zNN2GDG0ggunPZsDjKj0CIcMwvS0es3Aq1L11LIAqLc=,tag:MK7hM8pTTaQgA6Wravphxw==,type:str]
      - ENC[AES256_GCM,data:1nVRPPj5dQ==,iv:pAte8c5lYNjhWEVA/E8QEPh3GTmQpcWtOqSQbZ0rBe8=,tag:gMZMn4H0cz+UFJgr7vD1Wg==,type:str]
  jwt:
    providers:
      - name: ENC[AES256_GCM,data:skGQE4sh,iv:ndpnPzWqDfgOKh51EJzqn3jSMLEdSRbmbHo8ge/XBY0=,tag:h+5BaYFNl2axIR9c2NeGnQ==,type:str]
        issuer: ENC[AES256_GCM,data:ZdkAZ7+uayYKwQgrRslKRtSg6cxgzAlpnbKY,iv:BY4ujeGFz5uaX9Pl/qGeWr/3gc/ouBo58hi13FjrNvE=,tag:dtFKUolIrJ9OMLqzHrqzTA==,type:str]
        remoteJWKS:
          uri: ENC[AES256_GCM,data:dq0VIFKZs2magoqXu+5ojlD/jtItlFb/UcvPt1/S1WJ4qe/94uY+nkaH,iv:uOcgQWZRcmG58YV079Oi4tFY9o13thR0pCDTRvhWRjk=,tag:nTpDrEVTOMHfZ+WWfH1FDA==,type:str]
        extractFrom:
          cookies:
            - ENC[AES256_GCM,data:qrRwv8bVPQ==,iv:g5cMnz1uF/HS8Oj4u7+DDEI4ZdqckQWZluMnu0DamZA=,tag:bGFbIXfN3qS2lGG2DIZGKA==,type:str]
          headers:
            - name: ENC[AES256_GCM,data:05iuqxi3dRfCUMZpUQ==,iv:ScBllQGWMV+6HeLKDxyBWqfOKuP/t26ilo2Q5WF1mvI=,tag:7oifnF5ryn/KnDV6iV4/6A==,type:str]
              valuePrefix: ENC[AES256_GCM,data:2OxbweNg5A==,iv:+VrOlcT/kzuHXeWbfPgI0NRzSDeaQ016P3q95a8cqdw=,tag:3NBUWTsD0VZMIgEVWnF4Fw==,type:str]
          params:
            - ENC[AES256_GCM,data:Au+mAEUiCNGlWbY8,iv:uxLPgYyioy/Yrlm+gfXLVj4/1IENjap5fSqzZt1Ngqc=,tag:USJ4U7/cnlPTKbLt4cYA8A==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:ZIZq6g==,iv:W71hg4s5ZoFtTb11f5gUV+rgyWlZq2SFc5BZtSgVucI=,tag:zem0DGTHnj/SfiG7ZjAkrQ==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:UB4l8xaLmHl5ckSkGje1,iv:8qKgQIsvdP6YEvg5BdXQqqYmyguYOjmWZSrSVMC9tDY=,tag:Cne/C/lrYrYKWkn9knQw/A==,type:str]
        action: ENC[AES256_GCM,data:RaDaNs8=,iv:MdPmyvnqeBs3y9+cx/7da+0sd+TZfR7sBUEdhgMHFWk=,tag:mrzqRRkhS064XaiEImzsww==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:sbmnNZwA,iv:xXlg6KfJsSKE/WZMlOZFxx5gqO+Ydc8Fo2z1Gh3GY4Y=,tag:gKJ8sxrPNawusdU2j3wRoA==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:5sdEdCA=,iv:lSLza+tt7A3uI6yfOS6dgleP/EQGnmXffClTNYUeDeA=,tag:Eoz+kUsXCXkknuT7gKJ2cg==,type:str]
                values:
                  - ENC[AES256_GCM,data:CKW3EOktnKfqe39yBRKq+A==,iv:Ytf3hl1vFj1dew7uoukBnCptFyCRl44IeAhcevqR1wE=,tag:2bgmg+K70ritV0i6o0lEUw==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdDJaam9zb1FVcHVOQzVy
        Y1crWWFIaUF2czJGS09JZ1FtT3FWaDhlWlZnCkFDMHZpKzBXVFpJZSt2UGZEU0ph
        R0xzbjdUdlZWRUw3Q3RzN2xiRlBCc28KLS0tIEtzZU1oTzRkZUhPeHlFSnl5QXdX
        Ti9PaXVJNUNGeW1CL1NZd05FUFMydEUKaV/fDGZsViRmjwcytSu+OwvWdMOcbtxY
        w89yEeh9I/ijXDRIUct3D9pFLnq1M+rL0xdezmVP3lUdJynaRyTAHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T06:04:09Z"
  mac: ENC[AES256_GCM,data:WeMTVCmurZwgwxrptlgmeAEG1k7fy3YKSPyFJpwfzNEVEw81n5x2HeMGz9t0Jt/1Dzqfu0wHWqg6U34B7jFcrOERTiyNGafINAGCW6iO+fW5+naHivPK/xond+Oa3CuI7eRZ93yfWcutpq+QH1Cq3NOwPh1O/nJTlqBFVkcoU2U=,iv:fmVzj9j9FFFarV0OerJw6fx3lHBSPybfdrG8yShLOwM=,tag:qvnyhm9AxTR1nV9EWnENMw==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
