apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-internal-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:O065ENnvtvLxmaqWAdgybNT8aj/eaN9cUA==,iv:dgIG6BD/Dsl1Z3oUu7Jo54ww2RL/6Vg3B0hkhurzLH8=,tag:dLtx+VomxlakexhqvmvF3Q==,type:str]
      kind: ENC[AES256_GCM,data:S3dfSUBRgg==,iv:r5m7iW14/IhAfv5Vy872pft9rPbGBipC5MaZaLS/RPs=,tag:A8yISZS+tXJXQh0kj7eGAQ==,type:str]
      name: ENC[AES256_GCM,data:zUvx2IPodGwDJHYnrjt3DdJZwVA=,iv:seuWHVlMAU0lSaftVe4ZgxsfZ4wNZNyCdEOgK6O7eBM=,tag:xMxh5gVPQGLh77IhIwhSLA==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:2kIiDu6wMCiedwLINFCHiGI6zP4vYMk7hk4w,iv:nnYM0SaGxkN+1RTmDwiTG4w624mgF8RVMOzSuJgMRM0=,tag:JHt0n/bKJx5LSVBpWnQr3g==,type:str]
    clientID: ENC[AES256_GCM,data:vm1Q0cuqAQ31Xv+jIAfPehM+Ryt3vYmXhMI6F2MLkVjLnizd0chyHG2X+g==,iv:JZodexIyQNU3+Aq5XokHF7JLh9zbCMgogPBs0jzk/sw=,tag:ND8s7IgpJCJFch/dsX7UWg==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:hxzmcFkcnTrE77NGZR+tCEgBss6xCGqaELE=,iv:DHpmijBpQ3ZhgBituXihSZixy/er2F2jmHNv/0xAlzs=,tag:K6b3uOVd9BxefJaWVnryTQ==,type:str]
      namespace: ENC[AES256_GCM,data:gNuJAtbBFw==,iv:HejnValZPkYesywtO70G6IKHNWCYl/Cqjs3Qj6ad74M=,tag:FtSAJJLyJUnQdqGB06Il6A==,type:str]
    redirectURL: ENC[AES256_GCM,data:aPhBw/YD7H8zzqJusppKGHHB0/Rhk4OjmS0ztvewWVyVkqRY7vriVB5Kp1wJyIUR7Y/Fr13Dlw==,iv:+fDnsw2v28AsgSIIzPvy9WudfZW9fxbpH1S9rvzNpzE=,tag:0surEbLhlNg0Z1wwZK3zug==,type:str]
    logoutPath: ENC[AES256_GCM,data:5Djb3er06w==,iv:1JqdEcg8b/kdfIoYrqVt1mKsGXIUGhKtlhurYuhcrSI=,tag:yeddEmTnYj+7uNTjZXzG2w==,type:str]
    cookieDomain: ENC[AES256_GCM,data:So7106Ot7gnFz41SfqsTwQ==,iv:C/3S0lsWyDwCjQRDloiDv2uwZjriWyaZSHM7/Ge39zA=,tag:W1ar7J/S+DbcweLZEe6OkQ==,type:str]
  jwt:
    providers:
      - name: ENC[AES256_GCM,data:6Yzlb/yz,iv:fn8Y9etsc0NvGS19op5A+7kuvZes4aCCuWDNds+qUn8=,tag:8TroJE9D4Bt2gkebx5U/xw==,type:str]
        issuer: ENC[AES256_GCM,data:e7H7Mj4dxaM2pg2XXjZDpQo39TCiLOr60JgP,iv:KGNkULxHR0qXlrx3sLWIaOtm5cT0I5eCep4WAs0MJXc=,tag:5tZqywmLkVtXqnErj3XXJQ==,type:str]
        remoteJWKS:
          uri: ENC[AES256_GCM,data:MqFimqIZeigpw06w9ZzHYiYi1O8Z9UiQeCVtlMDNX0JvCCYK8l6evqFW,iv:ybz6mdQkoGRlj0UtGdtvG3kEkOssDrQYnCgRrQ/yAbs=,tag:BrMg74nQgitTciCoWx915A==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:iJx26A==,iv:c0XsylSSXMEdc44IEarP9T/Slp8lrCjoMIwON3VpmnI=,tag:Jm71vwcHgCCqqytPCCmo7A==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:vi+eC9J5jrH9H4k5n0Kl,iv:0dZ8lwCgDKA+R3+RO3VB7iPqi7BODaXATaitbkIaJjg=,tag:K9/S1RyihpjUEUA9KhU8Wg==,type:str]
        action: ENC[AES256_GCM,data:v89jY+o=,iv:Dokatd3/JI/FzuwhJJV+1Tmyum7Enr7q52nVoUjF41k=,tag:0J3IIT9AG3Kfg0q/nN+Ifw==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:IkQTwM4q,iv:2QqJ7QQSOrx8d8UhAeQeMdhHvA5u0UVEafcoOsKbz4M=,tag:0TvS3L1KAi/KDh7pwaX4zQ==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:P0zlbeAFqB8KP+tdMIY=,iv:8uS2DlLzeCPyDilE2jQVAmmcW5jooHNlM8VtjFw7LeQ=,tag:Vj6vYnqIVSzWKlMhV1ZbCA==,type:str]
                values:
                  - ENC[AES256_GCM,data:kBZJjA==,iv:hbdeEgPoYtElgdMLFMXr6uQjZ8a32DPHyJKyc9tShIk=,tag:s/m1oMXtCZqKm5edonYqAQ==,type:str]
              - name: ENC[AES256_GCM,data:HccIwcM=,iv:mTYaRAJty2TrTsBe6GQE8xLr710+9PmwAH0Ge4H6BEc=,tag:acLwSmMNJGEygpIlD2GRmQ==,type:str]
                values:
                  - ENC[AES256_GCM,data:FAK6msbzEXcbA/E0VmyJknx2N2zNU3hymUHuv+S51bQ=,iv:Adk9t0ghYghfK0nOJjDdixyO3rV9XHzvOdZFyear/HM=,tag:ykcQz7GtPkIUn4jKpR5viQ==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYis3TGZnbUZHeGRNRzl0
        UkwzRldpNVlnNjN5a0k3WWEzT1h5TFhjWGxnCjhRSGl4VjJOR3RZMzIyTC9oKzJJ
        Y1I0K0JGZmYyT01xQXBCZTRnVnZhVU0KLS0tIHI1R0lzTzg0eTJmZmpWTDhGYmY4
        R0F2QWc5Z3BnY3pmQ0RVN0E1VDBsSHMKQOZIP/2PJy1FH74TU2/PUAo5mhhFWINg
        zI4j9q7lk8J0sMw7gyhmT1O0Ul15M0YZp7ASI8sv2fKGX9HGyehC5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T06:27:23Z"
  mac: ENC[AES256_GCM,data:cFnAT3+dbsfweIvbkxrSLAlFdonkBpF4XniXs2CKZyEIOPlYxNM5FDBLsblPmpg0mr0rpQyjleqtjTgPTQwKjchAIsDzcqgNBsQlVmasmqnikVmO39DK/QWGV4xS4MP92GhJBXuBIRFJEt+j6UGQ1hpan1Vz0pjMRutrSqmlZPM=,iv:agSsk4xt1pRJi073RzQOTeLqbCiVpEteB5Fg2YDqbuA=,tag:4AO4+/d5UkRa3VZSQCUZ4A==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
