apiVersion: v1
kind: Secret
metadata:
  name: google-oauth-client-secret
  namespace: network
stringData:
  client-secret: ENC[AES256_GCM,data:EwX+kIUCGu+yj2oZ/PVIQcxOMr4opXEYnbUVxveBmgGhiqY=,iv:jLLvDczIQybyZbyzY1Imk9QtEncOB6Aal1JwWFgdRAI=,tag:4TeEqrr9A1BRPLkVSukxmQ==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQWNBeWY2ZW9hekUvakxT
        RWJKY0FxdFUzcGcwNmFoZ1BqcHBkM2ZTSVZFCkswTVI3N1JtMTh2eWlnWUEyZDdh
        QVRSZzd6dDdjWmZOV2FqeVpaS2xBbGMKLS0tIGxqbWl4QXRvVy9yUklSY2lSdGNy
        aGw3YUFMdmZiT1Nrd2djYmZKRzZHVXMK1/pUWaDBYdCjIQVXkNTUtmecDcXMVsfi
        1KV6yaAWRdln2EhKYHmVT3aZcRHInWc7hO8RJkg+F5j0215TddJK/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T04:59:24Z"
  mac: ENC[AES256_GCM,data:sg9JlURJc2otkelDn95ShbGwL7u6OcilOM/kJN3+fvZEKhxDVZRp+cG4BYBoM6GvoKJI/32YjPgwv9rKudKTkAU0c8MEDaZEUN/E+jBJ23TaSWa+3v3yE6xLpzKbwZXGy4l6i+Kchc960wUyHR9tEUrNp+viUVyhViOokHL7o78=,iv:+jL2a9k0wPPp5vTRZQzKiFHrYy2veDyuaVubgPO+/fQ=,tag:rLP9BEGP9Q5NY2s8Mo2dqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
