apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-external-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:MJP/wDK1PVxB2v40x++YXeJRwZB2dOKrvw==,iv:gPGIvRiyAwTRFaZCd2KDIrkyHrC74Fom1LmduSKILe8=,tag:oi/rsEf06+4IKV8USUPiYg==,type:str]
      kind: ENC[AES256_GCM,data:rEwvc16rJw==,iv:M9ZK5nEq64DpAXmE6mCnNUjqp/i0Cpj9Ib0LcvOQIxQ=,tag:xmcPWAnLTFdcL68bdT+1SA==,type:str]
      name: ENC[AES256_GCM,data:+yMafus+VObQ8nXAfie1fjykY98=,iv:mjoQkbkCuzHOcM3pappnBr35YJVEVoWCDrNe9dnbNjc=,tag:dsV/6ZZnsaSlRzcNF/8VFQ==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:4C8dXRJk5l4RHGdHohjVgWfV3NiyeLf6w0+f,iv:cyygsJdcQ7U2WBmWAJrVLz0Fz5Kjt0k7YnKuNl/6+xU=,tag:vw78OZsxLmK4WR/ZkPU8Dw==,type:str]
    clientID: ENC[AES256_GCM,data:3MM9fdvh36Qnb+Z/vHbqij9tJRZB3cnxH9vf6ugyIptJle2ijQ66Hp4Zig==,iv:lf4pidUoJPDBvIKNFRP28CtHGw/nxfLGLtS6IFUugdM=,tag:vkn3I+v0Ti/ggkAfxzIvHg==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:zfW5F5OyOZ/62ywsGjWVQ/knSj8GBXNP2hc=,iv:NoVe+1VXRQtdQ9KvyeKg1ZGAb08VKrR0kIgSmIZInwA=,tag:XANyruE0fJAwq3AA84kS2w==,type:str]
      namespace: ENC[AES256_GCM,data:wuhLRAly9w==,iv:UXgPM74gaFhFEIHI0JQiNynfgKLoYCs3rQHBNG3mG0Y=,tag:Clrm9ZYscBigHdnlRfF+5A==,type:str]
    redirectURL: ENC[AES256_GCM,data:c7T1IeMpT96NpP3H1hpxmZW/Snt0WwfmUzAB8BFbTapLnxzeUTjsQYJykibX7EUftSI5EWMDOA==,iv:ALV18HeXolrC7mZQiPoYhSsj2Bal2qNjHauKX8saHsk=,tag:6qbrzUpV0Chh6kw1V41MNw==,type:str]
    logoutPath: ENC[AES256_GCM,data:LJ6xmfrPlw==,iv:wmBjVTBAvmWZSomGbHBpDdLIVO/dLzVq3wWGIFplBmo=,tag:un6WHBk7z2MtnSadHINEEQ==,type:str]
    cookieDomain: ENC[AES256_GCM,data:WocQ8lKqPw4CGfETCEtWiQ==,iv:Hm/JamcNgSR5a73xg0Sjucv8CorWrjiuWop0G99hCh8=,tag:uXv9vx+GS7pmo29geXW0kg==,type:str]
  jwt:
    providers:
      - name: ENC[AES256_GCM,data:3S6dDD+v,iv:uV45HFR2COWNnK/7NwABS2lQ2VOV2h4GduRGTUs/vOQ=,tag:1ck/BmuHq7ItYwwMAuc2zA==,type:str]
        issuer: ENC[AES256_GCM,data:5qE1ZGQH2Z6ttjdTJirK+Y18iE/ks4AQQ+jc,iv:ruS7vLy34egwip6fGTrInFVWX61keytTiz8EgRp1W6A=,tag:5p2i+MgCCutMwxpxGi/oag==,type:str]
        remoteJWKS:
          uri: ENC[AES256_GCM,data:kfKJjBbTyrVT5A+nQyztiyCevMDuQnFc8Izm4co28wYDrR8/XKK9Ksc/,iv:OjW4/InfDxp7Grh3coqgj6d/X9bRLlC6cVkI8mvF1pA=,tag:hnaPtTfLttebVFmmmyk/DA==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:ZuEG/w==,iv:khdOAjVir6z2nYHLDhcNBiFRxJoLBJUy4jd5rpxOfOo=,tag:NrUnlQkSjhOa7g7KSbckBg==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:8gwso8ALZ1kD7wM6IcF3,iv:jBZiNEvbjhJwoa25ShWJcLhRIjhX3FAuaVRQMSkk+oE=,tag:ethBaUWtCx0s5N0gY1KySA==,type:str]
        action: ENC[AES256_GCM,data:IoNtI6w=,iv:9/+vVHKADDlXqRl1ujvDTddwN1jDkrcI78p4F9ItYos=,tag:O3f7JtnKV2n1rPBEshL7sw==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:yzgA4ylB,iv:1445pVvh+L4dkuAM8bxjMDkSqLJkvuayGUYWSRmRtiM=,tag:ojK9BnNLjIPZNklnEaniKA==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:Y2eQxu6B0ItT5Ltgws0=,iv:P6JqBqRUYCnPF/GqqICy7kEemy1qwL9vwRHBHjQxURE=,tag:p/Jl7O4PYGSsDlmye266yg==,type:str]
                values:
                  - ENC[AES256_GCM,data:VocIWQ==,iv:Nru22/2ikaJBH8uBRTxjdelpAPbjUP1sKZNeRyiSiwU=,tag:O8OYBndlrspJS8yTPqNnhA==,type:str]
              - name: ENC[AES256_GCM,data:un2Z9yI=,iv:J02tjRjUlYueXtpsnTKWFM+7/wprDSIAOvRBvYj3yaU=,tag:13f+Jlb12ekNOIN0Bf28+w==,type:str]
                values:
                  - ENC[AES256_GCM,data:zKFTP9nJELV7EAMIdEKf6BrSAuO14nY=,iv:GvPsg4ADfl4zJi3ktzXFazvoAzzNpsoJhkUCfqrzBFs=,tag:nftCN35yp/8BSmi09CQRaQ==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R3RHSGtFR1AwVy91enVh
        WWxxVlVaQmxzVHIvbHJldjl3OW0xWC9EWWhrCkx0TWtkV1RFdDZQUk1xcmJ4Sjlq
        MUc2bVIwR052WllpM3kxWlJHMnU3dTAKLS0tIGhNL0lEVVdDVlBUVWgxRVZJbUhI
        Yy9nbGYyRHpxZ24wNFJkU3VNL0p3NWMKKIYeMALZGRm+Qok4cJ+4U9MNu9obGlx6
        cpfKGTdCUS1vlz3MIsdj/veggvpUNQBZ3NEJ/MZEdZ0JFBbADIxsFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T06:27:23Z"
  mac: ENC[AES256_GCM,data:QtfBdtaIEo5DqpPRhXJDsXCjpozUViwN5tmDqf0UT9qrvBly103jdsbHzPOcxe3L/Prmjc3sCIBqYBDKPAbs4N9QFTTc1W3U6Pa8+nOdcoo2+aW71xM9Cnk445Xqf9I4w6wQLrKikc8Cx4ejknGBGxSIOSCbzwOARN4On4dyRBc=,iv:6D9s9QA3M7Mbzw1XjcrOqKR2E/O+ogRMSLTwYLnWPnQ=,tag:RJcAJuwfWULio5hHFSz31w==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
