apiVersion: ENC[AES256_GCM,data:iTc=,iv:jwZYonwBrVZxdEIZnDnm3UNTSJaiWOOVH6ELET026G0=,tag:s+QyBT+JpHI+ErZccnP32Q==,type:str]
kind: ENC[AES256_GCM,data:xAjQzJht,iv:5GH1bssdHLaES1hXXrJe11b98wHwLJUvnJifnBrG9YI=,tag:2EMQ0dbWNuKq/RGJLzZ9Vw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:K+u8KEOKCE2tf0ITdUNQnglZ9txAFmLh2bA=,iv:sGaZKfJfOcvkRZj03SkTRpEu8Dnvw9C2/H2FPDjEr5o=,tag:E2V1R2snGM7QG3j8/+/dzw==,type:str]
  namespace: ENC[AES256_GCM,data:SapeeE+z9w==,iv:Ta6QIKkiTIp5gksdz0RzeqAX1N/HgZFeYOj1gS285uo=,tag:rR/iX65N8wIGPqSTEMZ3jA==,type:str]
stringData:
  client-secret: ENC[AES256_GCM,data:mYWv5itnpgHPEp9SUi08LRjDEKy1xZYS1YB/yxRumfGXVI7xjJXRA9PoWcdNSHU=,iv:BnV0/Gxpyi8D5HHT426BNeJzwFceYt01Yqjn5fQlXrE=,tag:amgXDrcBfUXqIrgdboeNIw==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTWlLdndPUXY4OFdsUEl6
        VnJxanNTajFveUQ1Q01XUFVlWTlkOHhGRGtRCmVqNHBnN0w3Qm9yU1MrWEpnWUo0
        QXgxcnRnYlo1K0JaZmdVVWM0YTlYMVEKLS0tIDhnODBPZnFnVFE3VWZzVlQ5TjlQ
        dmFCb0w4b0sxVlFKUGtFU3NkOTVLWjAKT77bMpPxj38t59g8NHgRBZ6chXY19UKO
        pLaW8XqUOG8NZ8zJUZJ4pxFS9gpzSBxxrnM+/ol4i4p8GoBVBFNjlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T06:01:22Z"
  mac: ENC[AES256_GCM,data:7qVLdpDt14Xwzx7/mIkei83szF4tekChnFTLTmsklJ+pBmGwrNzFX5f0b9NNTXYsr33wxpAl81IWtEy/JbmjDEyd7JBvqKhNo9UxLWX1M4CagA58kWM7U1oXBzTwtnJwlF+dYlBDx22zkdYu9REA0tEu7pfELf21VoO7MnFoblI=,iv:dBoFxlrpEtCsvfcN4lpq2XykOlJPQ8cWPjmD+015oVg=,tag:pyx+53h5EF/wElcD6+tTNg==,type:str]
  unencrypted_suffix: _unencrypted
  mac_only_encrypted: true
  version: 3.11.0
