apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: envoy-oauth-external-policy
  namespace: network
spec:
  targetRefs:
    - group: ENC[AES256_GCM,data:fDvgZtODSCrYZ8Ufy0xOdo8r4S7gP7CH8w==,iv:FekebA1VaucNUato+6OFV+Mkgb764E+qT4WMGnVaai0=,tag:cYhLsWPUvlxv2yudyHUkxA==,type:str]
      kind: ENC[AES256_GCM,data:SwCjoHrrow==,iv:vivrngVr+a/F2PJjF8OiH3u2LQQxnIQGK8uYdBaHWNg=,tag:LZu8z7JMNeZqeq5IbcOedw==,type:str]
      name: ENC[AES256_GCM,data:swHBV2QvC//VKr908cJykwIo8Yo=,iv:RSI4ZMVs5+JhZ9gj3ECgblHf8m7R06mDXXl95hSPuno=,tag:irK67ubphhasXwkY+gycsQ==,type:str]
  oidc:
    provider:
      issuer: ENC[AES256_GCM,data:ay8p5tJXt0meNTWSmgB8Sgs2sKbf1Yqm82hq,iv:EcOmRyIUFA6wCe40H4sY5GNUDcJI+UUVNu/ieuAu4Pw=,tag:13PB8kGKF3kRb+9HbUoUSA==,type:str]
    clientID: ENC[AES256_GCM,data:bCHziiAhr+XXtxbYW9qB8avutMycvRSpH9Rc4n1IbVmff8+ybMjZlH1ETQ==,iv:lhtonkudVLVmGaCR7MOFlxt1f99I9DH8GP2ITL1bvAo=,tag:EVGH2Buuhu6zlTx02+pN5w==,type:str]
    clientSecret:
      name: ENC[AES256_GCM,data:z6NOWw+XAlZZN98Qf1sZZITEc5t6gGc5OSk=,iv:AE6NHUsPMJZaw9+tqC3gxFkBg2eM2Z3vQTLXJ5NQttg=,tag:BtWkqbn2iPWpL6TUJSsL2A==,type:str]
      namespace: ENC[AES256_GCM,data:xElg5q09kQ==,iv:BXmYjZPtyI5UhCnL0JUZmfb/4m6cujyZVgvUYoMjscw=,tag:JrKPB3t+ImwbEJkDlfvvjg==,type:str]
    redirectURL: ENC[AES256_GCM,data:ap7cTPUKsEmL7dSZEw+Tt9a2LrHOm8ZIhT/LezqxmbYwT9U5iCdid88C05pM18EZHyl+YRyAIg==,iv:MWAzeg9uTbMIwpCledM65bm4YCbYjmGdBU3HKYrMP9A=,tag:i0vLdaNPsRVz6zByrN5nWw==,type:str]
    logoutPath: ENC[AES256_GCM,data:yoSgIWe+pg==,iv:d8y3YMlRfTAZ7miSDMutFpq3JfxcriGAoS3MybUTcH0=,tag:maTvp49JcKs/+yCdlCtm0A==,type:str]
    cookieDomain: ENC[AES256_GCM,data:P9Bt3xoDV0w0MYYKe6eGSw==,iv:iTtVV8xrSMYSX9J8vhDvx4VMVoodwpfJwO/M9xibNTQ=,tag:UF0uhDv8JnShEESqVmb9KQ==,type:str]
  authorization:
    defaultAction: ENC[AES256_GCM,data:JE5erA==,iv:og0f3b2MWO6fj8kvImqS73tDn/ZFv8LAw77kiaCimy4=,tag:yLhjFqX4kNYTcuPJelly6g==,type:str]
    rules:
      - name: ENC[AES256_GCM,data:6Kp6Dj98Xr/31P5PpUIH,iv:BJaihAGJSxovMC/osJD5GuSUNlIyzu9p/T775rXedhA=,tag:EQX7BrxJYtaOPKm5fZeNqg==,type:str]
        action: ENC[AES256_GCM,data:jxuNagU=,iv:b7kWGtbpfoTzDopQrxXtbfxerRlHrxkZnMvzeGeGSxA=,tag:gat303+W9tkTmLGDBstMpQ==,type:str]
        principal:
          jwt:
            provider: ENC[AES256_GCM,data:MBelPY6K,iv:5CgK8MntVeObJw4t0lxUPpPu9TgItA2TamsA+DAkUwM=,tag:jzH/8KzRS9Y2rNz2pw8J+g==,type:str]
            claims:
              - name: ENC[AES256_GCM,data:809iDvLzAE2yW6R6lXE=,iv:W7FHyQebOOXjvMpdBqKwuLV5siWGsAvklnbJF1CYePQ=,tag:sP3GXfpl/I2Sm2z7ji41Pg==,type:str]
                values:
                  - ENC[AES256_GCM,data:AY9iJA==,iv:hycbtv+uKJkwvC4C2EZmNg9Uixa0TXFfaXpjFM39Wm8=,tag:UBapbDt8ZJPtpKrn7HpFyQ==,type:str]
              - name: ENC[AES256_GCM,data:CPjlPcM=,iv:OT0Z3BoDY+weoIQ43HsNfD4+Ce6ZBf1kSeG4stJhYAk=,tag:5SB23j/D2ux+/s+PEbUhrw==,type:str]
                values:
                  - ENC[AES256_GCM,data:G0DzuUJQYtFBVFObpoIHQHV8RW0uMQc=,iv:wZulitRN4cAql1197JP9PSeU9pDnxFknhs4gitY3Nic=,tag:4VpAuuXcCjYiarT5RjfOeg==,type:str]
sops:
  age:
    - recipient: age1d7ltdyge970mha3gqyenf9mrn8ezg60nexy99vzndvl592q2zcxqkytdwd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsODhkWEVvdXpZenJKYUtI
        VU1XSEFKTU51ZTdkdjRaRVUrQjdDQXN5ckhnCis0aWRleUs2ZnpHcEtnU2VSbklu
        R2UxRjIyZk5CWW1pMXlCVTNvTjNjMW8KLS0tIEFKYkVudm56ZTFsVHg0VmJqY0N0
        WmdiQ2lYZHYzNEVBNjY3R3U3d0NBMWcKfQW4SVaZWCmVi075tTc056b5b1PQxAaO
        Kv60VV0VCG7+EMTSXPRDlSFb6hAjizfPAMPBZDIDCL1/SUhyIegN+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T06:24:46Z"
  mac: ENC[AES256_GCM,data:q7Z+Pj8v39hZEaxvhzAIPqEO6gBSaulX3RDEMQLEKqx2758pxCi+FUh6a0WgPGqdGxJpexXQb816pIFhIqG9wsvd7ydpd/DWHYr3sz5j0bWK1F2QRTEbclkJbxNjOp1hjTfle52OawwhNnIkrSnh5cmTUMevtSUeWFmiPImbACQ=,iv:XrOTc/DrvIwjeNRaFhqibfT5rYdYoCuD30npIsPxASw=,tag:d09g3WUogQy0JKOsVSwzyQ==,type:str]
  encrypted_regex: ^(spec)$
  mac_only_encrypted: true
  version: 3.11.0
